### ISSUE TITLE
Leverage AWS EC2 Image Builder instead of custom pcluster ami-create

### ISSUE THREAD

**Issue by brainstorm** [aws/aws-parallelcluster#1903]
I am setting up and maintaining a pcluster for @umccr and after trying to upgrade to the new [2.8.0 release](https://aws.amazon.com/about-aws/whats-new/2020/07/aws-parallelcluster-2-8-0/) (from 2.6.1) I'm faced with:

```
% ./bin/start_cluster.sh testcluster5
Beginning cluster creation for cluster: testcluster5
Creating stack named: parallelcluster-testcluster5
Status: parallelcluster-testcluster5 - ROLLBACK_IN_PROGRESS
Cluster creation failed.  Failed events:
  - AWS::AutoScaling::AutoScalingGroup ComputeFleet Resource creation cancelled
  - AWS::CloudFormation::WaitCondition MasterServerWaitCondition Received FAILURE signal with UniqueId i-0aefe545051e1fba5
```

Which I haven't digged through hard with it with `--norollback` and grabbing the relevant logfiles as issue #1902 suggests, but I suspect it's going to be related with custom AMI issues, [as many issues on this bugtracker hint towards](https://github.com/aws/aws-parallelcluster/issues?q=is%3Aissue+custom+ami+is%3Aclosed+)

Now, since customers will continue doing customs AMIs anyway, wouldn't it be nice to have an **EC2 AMI builder component** that ensures that the latest configuration on the parallel cluster AMIs (custom or managed) are properly deployed and sound? Here's mine (in progress) for instance:

![Screen Shot 2020-07-28 at 3 07 23 pm](https://user-images.githubusercontent.com/175587/88621608-3e072d00-d0e4-11ea-9edc-6ff08ad4bc2d.png)

As @demartinofra points out:

> To make this even more clear for customers we are working on introducing additional validations so that this is prevented by the CLI at cluster creation time.

Wouldn't it make sense to leverage the (managed) EC2 AMI builder instead of baking further custom logic into the pcluster chef & co CLI? At least as a base configuration/validation, later on customers can indeed go nuts with Chef and other IaC tools.

**Comment by brainstorm** [comment]
For reference, here's the current deployment and operation scripts (running on Amazon Linux 2020-07 AMI):

https://github.com/umccr/infrastructure/tree/master/parallel_cluster

And the current logfiles after launching with `--no-rollback` so that I could examine the issue post-Cfn-failure:

[cfn-init.log](https://github.com/aws/aws-parallelcluster/files/4986180/cfn-init.log)
[cloud-init-output.log](https://github.com/aws/aws-parallelcluster/files/4986181/cloud-init-output.log)
[cloud-init.log](https://github.com/aws/aws-parallelcluster/files/4986182/cloud-init.log)

The underlying errors might be unrelated with 2.8.0 upgrade (since I've been performing other changes) but the EC2 Image builder point still stands: gives cluster power users easy access to install new software via rolling new AMIs on the web console, super handy!

**Comment by demartinofra** [comment]
Hi Roman,

thanks for opening this and proposing a potential approach to improve the custom AMI creation functionalities in ParallelCluster. 

You are right in the fact that adding a validation to prevent a user from using an incorrect AMI with ParallelCluster is not going to improve the overall story of building you own custom AMI. However this is a simple validation/check that can save customers hours of debugging and that we can quickly introduce in the upcoming version.

Now going back to your suggestion of improving the custom AMI building workflow by eventually leveraging EC2 Image builder as the tool, I think that makes a lot of sense and it is something we are already evaluating as part of our broader goal that aims to improve the customer experience when customizing ParallelCluster AMIs. For this I'm going to mark the issues as a request for enhancement so that we can make sure we consider your use-case when designing the new feature. Thank you for sharing with us the work you've been doing for your customer, it'll be for sure a valid source of inspiration!

Last but not least, looking at the error from the logs you shared, it seems like there is something broken with the python virtualenv that ParallelCluster configures for recipes execution and this is most likely related to a `custom_ami` you are using.
>---- Begin output of /opt/parallelcluster/pyenv/versions/3.6.9/envs/cookbook_virtualenv/bin/aws fsx --region ap-southeast-2 describe-file-systems --file-system-ids fs-09a50ce6a2a522df2 --query 'FileSystems[0].LustreConfiguration.MountName' --output text ----
STDOUT: 
STDERR: sh: /opt/parallelcluster/pyenv/versions/3.6.9/envs/cookbook_virtualenv/bin/aws: No such file or directory

If you need further support on that we need additional info on your cluster config and custom_ami setup.

Cheers,
Francesco

**Comment by brainstorm** [comment]
Thanks for the feedback!

> You are right in the fact that adding a validation to prevent a user from using an incorrect AMI with ParallelCluster is not going to improve the overall story of building you own custom AMI. However this is a simple validation/check that can save customers hours of debugging and that we can quickly introduce in the upcoming version.

Hey, I wasn't arguing against, I was agreeing with the approach: give customers a "known, working and validated base" of pcluster and let them carry on with custom AMIs thereafter ;)

Now my cluster config and current status (as of today):

cluster config: https://github.com/umccr/infrastructure/blob/master/parallel_cluster/conf/config
custom_ami (component) setup:

```yaml
name: Bioinformatics
description: Bioinformatics software and dependencies
schemaVersion: 1.0

phases:
  - name: build
    steps:
      - name: base-extras
        action: ExecuteBash
        inputs:
          commands:
            - yum install -y amazon-linux-extras
            - yum install -y tmux htop vim
            - amazon-linux-extras enable R3.4 epel vim docker=latest rust1
            - pip3 install aws-parallelcluster --upgrade --user
            - mkdir -p /scratch && chown ec2-user:ec2-user /scratch
      # https://github.com/dcbark01/AnacondaInstallEC2/blob/master/install.sh
      - name: anaconda
        action: ExecuteBash
        inputs:
          commands:
            - su - ec2-user -c "wget https://repo.anaconda.com/archive/Anaconda3-2020.07-Linux-x86_64.sh && chmod +x *.sh"
            - su - ec2-user -c "./Anaconda3-2020.07-Linux-x86_64.sh -b -p /home/ec2-user/.anaconda3"
            - su - ec2-user -c "rm /home/ec2-user/Anaconda3-*.sh"
            - su - ec2-user -c "echo '. /home/ec2-user/.anaconda3/etc/profile.d/conda.sh' >> /home/ec2-user/.bashrc"
      - name: facets-biocontainer
        action: ExecuteBash
        inputs:
          commands:
            - docker pull "quay.io/biocontainers/r-facets:0.5.14--r40he991be0_3"
```

Current errors after further fixing/debugging seem to be related to parallelcluster trying to instal `dpkg-dev`???... on an Amazon Linux 2 instance? (`arn:aws:imagebuilder:ap-southeast-2:aws:image/amazon-linux-2-x86/x.x.x` **which is latest 2020-06 Amazon Linux 2, the 2020-07, present yesterday, seems to be gone today from the EC2 Image Builder web console**):

```shell
(...)
Recipe: aws-parallelcluster::base_install
  * yum_package[vim, ksh, tcsh, zsh, openssl-devel, ncurses-devel, pam-devel, net-tools, openmotif-devel, libXmu-devel, hwloc-devel, tcl-devel, automake, autoconf, pyparted, libtool, httpd, boost-devel, mlocate, atlas-devel, fftw-devel, libffi-devel, dkms, mysql-devel, libedit-devel, postgresql-devel, postgresql-server, sendmail, cmake, byacc, libglvnd-devel, mdadm, libgcrypt-devel, libevent-devel, glibc-static, libdb-devel, system-lsb, libxml2-devel, perl-devel, dpkg-dev, tar, gzip, bison, flex, gcc, gcc-c++, patch, rpm-build, rpm-sign, system-rpm-config, cscope, ctags, diffstat, doxygen, elfutils, gcc-gfortran, git, indent, intltool, patchutils, rcs, subversion, swig, systemtap, curl, jq, wget, python-pip] action install
    * No candidate version available for dpkg-dev
    * No candidate version available for dpkg-dev
    * No candidate version available for dpkg-dev
    * No candidate version available for dpkg-dev
    * No candidate version available for dpkg-dev
    * No candidate version available for dpkg-dev
    * No candidate version available for dpkg-dev
    * No candidate version available for dpkg-dev
    * No candidate version available for dpkg-dev
    * No candidate version available for dpkg-dev
    * No candidate version available for dpkg-dev
    ================================================================================
    Error executing action `install` on resource 'yum_package[vim, ksh, tcsh, zsh, openssl-devel, ncurses-devel, pam-devel, net-tools, openmotif-devel, libXmu-devel, hwloc-devel, tcl-devel, automake, autoconf, pyparted, libtool, httpd, boost-devel, mlocate, atlas-devel, fftw-devel, libffi-devel, dkms, mysql-devel, libedit-devel, postgresql-devel, postgresql-server, sendmail, cmake, byacc, libglvnd-devel, mdadm, libgcrypt-devel, libevent-devel, glibc-static, libdb-devel, system-lsb, libxml2-devel, perl-devel, dpkg-dev, tar, gzip, bison, flex, gcc, gcc-c++, patch, rpm-build, rpm-sign, system-rpm-config, cscope, ctags, diffstat, doxygen, elfutils, gcc-gfortran, git, indent, intltool, patchutils, rcs, subversion, swig, systemtap, curl, jq, wget, python-pip]'
    ================================================================================

    Chef::Exceptions::Package
    -------------------------
    No candidate version available for dpkg-dev

    Resource Declaration:
    ---------------------
    # In /etc/chef/local-mode-cache/cache/cookbooks/aws-parallelcluster/recipes/base_install.rb

     56: package node['cfncluster']['base_packages'] do
     57:   retries 10
     58:   retry_delay 5
     59: end
     60:

    Compiled Resource:
    ------------------
    # Declared in /etc/chef/local-mode-cache/cache/cookbooks/aws-parallelcluster/recipes/base_install.rb:56:in `from_file'
```

[cfn-init.log](https://github.com/aws/aws-parallelcluster/files/4992578/cfn-init.log)
[cloud-init-output.log](https://github.com/aws/aws-parallelcluster/files/4992579/cloud-init-output.log)
[cloud-init.log](https://github.com/aws/aws-parallelcluster/files/4992580/cloud-init.log)
