### ISSUE TITLE
mssh (ec2-instance-connect) or ssm support ?

### ISSUE THREAD

**Issue by elgalu** [aws/aws-parallelcluster#2436]
Is there any mssh [ec2-instance-connect](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-set-up.html) or [ssm](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started-enable-ssh-connections.html) support to avoid managing multi-user ssh keys?

**Comment by tilne** [comment]
Hi @elgalu. We don't currently offer this support, but it's something that we're evaluating for inclusion in future versions. I'm going to mark this as a feature request.

**Comment by tilne** [comment]
After looking a bit more into this I see [from this documentation](https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-install-ssm-agent.html) that the SSM agent is preinstalled by default on all of the Ubuntu and Amazon Linux versions that ParallelCluster supports.

On a v2.10.1 cluster using the default Amazon Linux 2 AMIs v2.10.1 I found that the SSM  agent was running by default and that I was able to connect to the instance via SSM. In order to do so I had to add the following line to my configuration file:
```ini
additional_iam_policies = arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
```

**Comment by elgalu** [comment]
Thanks @tilne ! , I've just realized ssm won't help my multi-users use case as they'll all end-up logged into the machines as the same user.

It seems ec2-instance-connect has better chances of multi-user proper access control:

```
    - Effect: "Allow"
      Resource: "arn:aws:ec2::${AWS::AccountId}:instance/*"
      Action:
        - "ec2-instance-connect:SendSSHPublicKey"
      Condition:
        StringEquals:
          ec2:osuser:
            - elgalu
            - root #admins only
      Principal:
        AWS: "arn:aws:iam::${AWS::AccountId}:elgalu"
```
