### ISSUE TITLE
Cross-account Hosted Zone for v3.0

### ISSUE THREAD

**Issue by gallanik** [aws/aws-parallelcluster#3425]
I am trying to create a cluster with pre-existing hosted zone, but in a different account. The hosted zone is public and the IAM role attached to the EC2 machine which I am using to start a PC has route53:Get* permissions on all resources (*). Since Route53 does not support resource-based policy, there is nothing like whitelisting the account ID in R53 Hosted Zone.
Does v3.0 support cross-account public hosted zone? and If yes, what changes have to be made in order to get this to work.

cluster-config.yaml
```
Region: us-east-1
Image:
  Os: alinux2
HeadNode:
  InstanceType: t2.micro
  Networking:
    SubnetId: subnet-xxxx1111
  Ssh:
    KeyName: my-keypair
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    ScaledownIdletime: 10
    Dns:
      HostedZoneId: xx12345
  SlurmQueues:
  - Name: def-q
    ComputeResources:
    - Name: t2micro
      InstanceType: t2.micro
      MinCount: 0
      MaxCount: 2
    Networking:
      SubnetIds:
      - subnet-xxxx1111
  - Name: spot-q
    ComputeResources:
    - Name: t2micro
      InstanceType: t2.micro
      MinCount: 0
      MaxCount: 2
    Networking:
      SubnetIds:
      - subnet-xxxx1111
```

**Comment by gallanik** [comment]
We are an enterprise dealing with a huge estate of AWS Accounts and hundreds of projects/teams utilizing these accounts. We have a central services account, which has the public hosted zone which can be used by anyone within the company. Having a separate private hosted zone per account will create unnecessary complexity. 

I tried to disable DNS (DisableManagedDns: true) in the cluster config, and the cluster was created successfully, but now it fails while creating the compute nodes. Do I have to do anything else?

```
[2021-11-02T11:59:16.872] Requeuing JobId=2
--
[2021-11-02T11:59:16.872] update_node: node def-q-dy-t2micro-1 state set to DOWN
[2021-11-02T11:59:16.896] error: get_addr_info: getaddrinfo() failed: Name or service not known
[2021-11-02T11:59:16.896] error: slurm_set_addr: Unable to resolve "def-q-dy-t2micro-1"
[2021-11-02T11:59:16.896] error: fwd_tree_thread: can't find address for host def-q-dy-t2micro-1, check slurm.conf
[2021-11-02T11:59:24.879] update_node: node def-q-dy-t2micro-1 reason set to: Scheduler health check failed
[2021-11-02T11:59:24.879] update_node: node def-q-dy-t2micro-1 state set to DOWN
[2021-11-02T11:59:24.912] update_node: node def-q-dy-t2micro-1 reason set to: Scheduler health check failed
[2021-11-02T11:59:24.912] powering down node def-q-dy-t2micro-1
```

**Comment by hanwen-pcluste** [comment]
When creating a Slurm cluster, ParallelCluster creates a private Route53 hosted zone that is used to resolve the custom compute nodes hostnames (e,g, `{queue_name}-{st|dy}-{compute_resource}-{N}`). If Route53 is disabled, ParallelCluster needs to be configured to use the default EC2 hostnames (e.g. `ip-1-2-3-4`). To do so, apply these settings to your cluster configuration (in addition to `DisableManagedDns: true`):
```
DevSettings:
  Cookbook:
    ExtraChefAttributes: |
      {"cluster": {"use_private_hostname": "true"}}
```

Please be aware of that this setup is not officially supported and not fully tested. It is known that MPI jobs using `srun` with OpenMPI will stuck/fail because of being unable to resolve the hostnames. So please use `srun` with Intel MPI and monitor the jobs in case they are stuck.

Thank you!
Hanwen
