### ISSUE TITLE
running into ec2 Client.InternalError: Client error on launch with Compute nodes

### ISSUE THREAD

**Issue by keien** [aws/aws-parallelcluster#3667]
- AWS ParallelCluster version [e.g. 2.9.0]: 3.0.2
 - Cluster name: pcluster-test
 - [Optional] Arn of the cluster CloudFormation main stack: arn:aws:cloudformation:us-west-2:171496337684:stack/cpu-test/f3aba230-7647-11ec-a01a-069e01da2417

Configuration:
```
Region: us-west-2
Monitoring:
  DetailedMonitoring: true  # false
  Logs:
    CloudWatch:
      Enabled: true  # true
      RetentionInDays: 30  # 14
      DeletionPolicy: Retain
  Dashboards:
    CloudWatch:
      Enabled: true  # true
Image:
  Os: centos7
  CustomAmi: ami-09497ab22d610eaa0
HeadNode:
  InstanceType: m5.large
  Networking:
    SubnetId: subnet-00bbd054b223b7501
    ElasticIp: false
    AdditionalSecurityGroups:
      - sg-74e42c12
  LocalStorage:
    RootVolume:
      Size: 127
      DeleteOnTermination: true
  Ssh:
    KeyName: ec2-admin
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
      - Policy: arn:aws:iam::171496337684:policy/pcluster-decrypt-ebs
  CustomActions:
    OnNodeConfigured:
      Script: s3://cb-parallelcluster/head_post.sh
      Args:
        - arg1
        - arg2
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    ScaledownIdletime: 10
  SlurmQueues:
    - Name: cpu
      CapacityType: ONDEMAND
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 127
      Networking:
        SubnetIds:
          - subnet-00bbd054b223b7501
        SecurityGroups:
          - sg-74e42c12
      ComputeResources:
        - Name: m5-large
          InstanceType: m5.large
        - Name: m5-4xlarge
          InstanceType: m5.4xlarge
        - Name: m5-12xlarge
          InstanceType: m5.12xlarge
        - Name: m5-24xlarge
          InstanceType: m5.24xlarge
      CustomActions:
        OnNodeConfigured:
          Script: s3://cb-parallelcluster/node_post.sh
          Args:
            - arg1 arg2
```

**Bug description and how to reproduce:**
The cluster creation succeeds and the head node comes up, but when I try to start a job and spin up a compute node, it fails:
```
srun: error: Node failure on cpu-dy-m5large-1
srun: Force Terminated job 2
srun: error: Job allocation 2 has been revoked
```

Looking at slurm_resume on the head node, it does think it brought it up successfully, but on the EC2 console, the node has a state down reason of ec2 Client.InternalError: Client error on launch

Searching online points towards something about issues decrypting EBS volume and KMS access, so I tried adding a policy that grants more KMS permissions, but that didn't seem to work either - it also doesn't seem like it should be necessary because I created the image using pcluster build-image and part of that config was encrypting it:
```
Build:
  InstanceType: m5.4xlarge
  ParentImage: ami-0a32ea36b1a39432e
  SubnetId: subnet-00bbd054b223b7501
  SecurityGroupIds:
    - sg-74e42c12
Image:
  RootVolume:
    Encrypted: true
    KmsKeyId: alias/ebs-cmk
```
