### ISSUE TITLE
Using API file with CLI

### ISSUE THREAD

**Issue by coderodyhpc** [aws/aws-parallelcluster#3803]
Hello,
I'm transitioning to v3.1.1. I was using the API but also need to use the CLI. The API configuration file reads:
```
HeadNode:
  InstanceType: t2.micro
  Ssh:
    KeyName: xxxxxxx
  Networking:
    SubnetId: subnet-xxxxxx
  LocalStorage:
    RootVolume:
      Size: 150
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: queue0
      ComputeResources:
        - Name: queue0-c5large
          MinCount: 2
          MaxCount: 6
          InstanceType: c5.large
          DisableSimultaneousMultithreading: true
      Networking:
        SubnetIds:
          - subnet-xxxxxxx
        PlacementGroup:
          Enabled: true
Region: us-east-1
Image:
  Os: ubuntu2004 
```
The problem occurs when using this file as the input file (cluster-config.yaml) for the CLI. The system output is: 
```
{
  "message": "Unable to find node executable. Node.js is required by the AWS CDK library used by ParallelCluster, see installation instructions here: https://docs.aws.amazon.com/parallelcluster/latest/ug/install-v3.html"
}
```
My first question is whether API configuration files are supposed to work with the CLI.
Thanks.
