### ISSUE TITLE
Error encountered during build of chefPrepEnv

### ISSUE THREAD

**Issue by joehellmersNOAA** [aws/aws-parallelcluster#3894]
AWS ParallelCluster version: **3.1.2**

Cluster Configuration:
```
Region: us-east-1
Image:
  Os: alinux2
HeadNode:
  InstanceType: t2.micro
  Networking:
    SubnetId: subnet-0aa9d3bd709f86d50
    SecurityGroups:
    - sg-045290f659c3be158
  Ssh:
    KeyName: pcluster
  Iam:
    InstanceRole: arn:aws:iam::716453263077:role/AmazonSSMRoleForAutomationAssumeQuickSetup


Scheduling:
  Scheduler: slurm
  SlurmSettings:
    Dns:
      DisableManagedDns: true
      UseEc2Hostnames: true
  SlurmQueues:
  - Name: oar
    ComputeResources:
    - Name: t2micro
      InstanceType: t2.micro
      MinCount: 1
      MaxCount: 10
    Networking:
      SubnetIds:
      - subnet-0aa9d3bd709f86d50
      SecurityGroups:
      - sg-045290f659c3be158
    Iam:
      InstanceRole: arn:aws:iam::716453263077:role/AmazonSSMRoleForAutomationAssumeQuickSetup

```
Cluster name: **test-cluster**

Describe Cluster Output:
```
{
  "creationTime": "2022-03-18T16:13:42.670Z",
  "headNode": {
    "launchTime": "2022-03-18T16:16:21.000Z",
    "instanceId": "i-0d46daa16277ef29b",
    "instanceType": "t2.micro",
    "state": "running",
    "privateIpAddress": "10.102.8.80"
  },
  "version": "3.1.2",
  "clusterConfiguration": {
    "url": "https://parallelcluster-e2ca1557272da85b-v1-do-not-delete.s3.amazonaws.com/parallelcluster/3.1.2/clusters/test-cluster-2gk3wqecfyzsjmvm/configs/cluster-config.yaml?versionId=yLZzRZXzmMhqwpQc2YyqZWL6ypW5MnvJ&AWSAccessKeyId=XXXXX&Signature=XXXX&Expires=1647624263"
  },
  "tags": [
    {
      "value": "3.1.2",
      "key": "parallelcluster:version"
    }
  ],
  "cloudFormationStackStatus": "CREATE_FAILED",
  "clusterName": "test-cluster",
  "computeFleetStatus": "UNKNOWN",
  "cloudformationStackArn": "arn:aws:cloudformation:us-east-1:716453263077:stack/test-cluster/6120e280-a6d6-11ec-b9af-0e4b061813b3",
  "lastUpdatedTime": "2022-03-18T16:13:42.670Z",
  "region": "us-east-1",
  "clusterStatus": "CREATE_FAILED"
}

```
Arn of the cluster CloudFormation main stack: **See Above**

**Bug description and how to reproduce:**
Used the above configuration and the chef script failed.

[chef-client.log](https://github.com/aws/aws-parallelcluster/files/8306267/chef-client.log)
[cfn-init.log](https://github.com/aws/aws-parallelcluster/files/8306268/cfn-init.log)
[cloud-init.log](https://github.com/aws/aws-parallelcluster/files/8306269/cloud-init.log)

**Additional context:**
Creating cluster on pre-existing private VPC/subnet with a role we use for all of our instances.

The Role includes policies
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iam:CreateInstanceProfile",
                "iam:ListInstanceProfilesForRole",
                "iam:PassRole",
                "ec2:DescribeIamInstanceProfileAssociations",
                "iam:GetInstanceProfile",
                "ec2:DisassociateIamInstanceProfile",
                "ec2:AssociateIamInstanceProfile",
                "iam:AddRoleToInstanceProfile"
            ],
            "Resource": "*"
        }
    ]
}
```

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iam:ListRoles",
                "config:DescribeConfigurationRecorders",
                "compute-optimizer:GetEnrollmentStatus",
                "support:DescribeTrustedAdvisorChecks"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "ssm:UpdateServiceSetting",
                "ssm:GetServiceSetting"
            ],
            "Resource": [
                "arn:aws:ssm:*:*:servicesetting/ssm/opsitem/ssm-patchmanager",
                "arn:aws:ssm:*:*:servicesetting/ssm/opsitem/EC2",
                "arn:aws:ssm:*:*:servicesetting/ssm/opsdata/ExplorerOnboarded",
                "arn:aws:ssm:*:*:servicesetting/ssm/opsdata/Association",
                "arn:aws:ssm:*:*:servicesetting/ssm/opsdata/OpsData-TrustedAdvisor",
                "arn:aws:ssm:*:*:servicesetting/ssm/opsdata/ComputeOptimizer",
                "arn:aws:ssm:*:*:servicesetting/ssm/opsdata/SupportCenterCase"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "iam:CreateServiceLinkedRole"
            ],
            "Resource": "arn:aws:iam::*:role/aws-service-role/ssm.amazonaws.com/AWSServiceRoleForAmazonSSM"
        }
    ]
}

```
