### ISSUE TITLE
API doesn't allow deletion

### ISSUE THREAD

**Issue by sean-smith** [aws/aws-parallelcluster#4031]
**Required Info:**
 - AWS ParallelCluster version [e.g. 3.1.1]: `3.1.2`

**Bug description and how to reproduce:**
When deleting a cluster with pcluster API, I get:

```bash
API: iam:DetachRolePolicy User: arn:aws:sts::905784713722:assumed-role/WX-parallelclusterapiNeste-ParallelClusterUserRole-OWFSQ9VL7CL1/WX-parallelclusterapiNeste-ParallelClusterFunction-NQNwoIOyf6tT is not authorized to perform: iam:DetachRolePolicy on resource: role api-cluster-2022-05-09-17-46-53-RoleHeadNode-EXNM6B7GER1S because no identity-based policy allows the iam:DetachRolePolicy action
```

Wondering if we can add `iam:DetachRolePolicy` to the `ParallelClusterUserRole` created by the API?

In the cluster's config I've set the following `AdditionalIamPolicies`:

```yaml
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - Policy: arn:aws:iam::aws:policy/AmazonS3FullAccess
      - Policy: arn:aws:iam::aws:policy/AmazonFSxFullAccess
      - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
```
