### ISSUE TITLE
Build image hangs on interactive prompt

### ISSUE THREAD

**Issue by popgendad** [aws/aws-parallelcluster#4058]
AWS ParallelCluster version: 3.1.4

**Bug description and how to reproduce:**
Build image hangs on ubuntu because install of `openssh-server`, debconf brings up interactive prompt. It happens when `UpdateOsPackages: True` or `UpdateOsPackages: False`

Build command:
```
pcluster build-image --image-id XXX --image-configuration XXX.yaml --region XXX
```

Build config file:
```
Region: XXX
Build:
  InstanceType: m6g.large
  SubnetId: XXX
  ParentImage: ami-XXX
  Iam:
    InstanceRole: arn:aws:iam::XXXX
  Components:
    - Type: arn
      Value: arn:aws:imagebuilder:XXX
  UpdateOsPackages:
    Enabled: False
  SecurityGroupIds:
    - sg-XXX
Image:
  Name: cluster-ami
  RootVolume:
    Size: 35
    Encrypted: False
```

Image build log where process hangs:
```
    {
      "message": "Stdout: Setting up openssh-server (1:8.2p1-4ubuntu0.5) ...",
      "timestamp": "2022-05-23T17:16:52.804Z"
    },
    {
      "message": "Stdout: debconf: unable to initialize frontend: Dialog",
      "timestamp": "2022-05-23T17:16:53.076Z"
    },
    {
      "message": "Stdout: debconf: (TERM is not set, so the dialog frontend is not usable.)",
      "timestamp": "2022-05-23T17:16:53.076Z"
    },
    {
      "message": "Stdout: debconf: falling back to frontend: Readline",
      "timestamp": "2022-05-23T17:16:53.076Z"
    },
    {
      "message": "Stdout: Configuring openssh-server",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout: --------------------------",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout: ",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout: A new version (/tmp/filefswXVy) of configuration file /etc/ssh/sshd_config is ",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout: available, but the version installed currently has been locally modified.",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout: ",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout:   1. install the package maintainer's version",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout:   2. keep the local version currently installed",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout:   3. show the differences between the versions",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout:   4. show a side-by-side difference between the versions",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout:   5. show a 3-way difference between available versions",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout:   6. do a 3-way merge between available versions",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout:   7. start a new shell to examine the situation",
      "timestamp": "2022-05-23T17:16:53.180Z"
    },
    {
      "message": "Stdout: ",
      "timestamp": "2022-05-23T17:16:53.180Z"
    }
```
