### ISSUE TITLE
Fails to tag SharedStorage ebs volume

### ISSUE THREAD

**Issue by jcabraham** [aws/aws-parallelcluster#4102]
My company requires all resources to be tagged, and my stack is failing because my SharedStorage volume is not getting the tag (in this case, {"Application": "jca-pcluster-personal"}). All the instances and volumes get the tag, but Here's the pcluster config.yaml section:

```
> pcluster version
{
  "version": "3.1.4"
}

```
```
Tags:
  - Key: Application
    Value: jca-pcluster-personal
SharedStorage:
  - MountDir: /programs
    Name: programs
    StorageType: Ebs
    EbsSettings:
      VolumeType: gp3
      Size: 35
      Encrypted: true
      DeletionPolicy: Retain
```

Here's the corresponding CloudFormation stack items:

```
TagSpecifications:
- ResourceType: instance
  Tags:
  - Key: Application
    Value: jca-pcluster-personal
...
- ResourceType: volume
  Tags:
  - Key: Application
    Value: jca-pcluster-personal
...
  EBS0:
    DeletionPolicy: Retain
    Properties:
      AvailabilityZone: us-east-1a
      Encrypted: true
      Iops: 3000
      Size: 35
      Tags:
      - Key: Name
        Value: programs
      Throughput: 125
      VolumeType: gp3
    Type: AWS::EC2::Volume
```
