### ISSUE TITLE
create-cluster fails with parsing error

### ISSUE THREAD

**Issue by zcobell** [aws/aws-parallelcluster#4139]
Please make sure to add the following data in order to facilitate the root cause detection.

**Required Info:**
 - AWS ParallelCluster version [e.g. 3.1.1]: 3.1.4
 - Full cluster configuration without any credentials or personal data.  
 - Cluster name: `test_cluster`
 - Output of `pcluster describe-cluster` command.
 - [Optional] Arn of the cluster CloudFormation main stack:

**Bug description and how to reproduce:**
Executed command: 
```
pcluster create-cluster -c config -n my_cluster_name
```

Command fails with the following:
``` json
{
  "message": "Expecting value: line 1 column 1 (char 0)"
}
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/{username}/miniconda3/envs/aws/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 284, in stop
    self._process.stdin.close()
BrokenPipeError: [Errno 32] Broken pipe

```

Cluster Configuration: 
```yaml
Region: us-east-1
Image:
  Os: alinux2
Tags:
  - Key: PROJECT_ID
    Value: id_code
SharedStorage:
  - MountDir: /shared
    Name: default-ebs
    StorageType: Ebs
HeadNode:
  InstanceType: c5.2xlarge
  Networking:
    SubnetId: subnet-xxxx
    ElasticIp: false
  Ssh:
    KeyName: ssh_key
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: compute
      ComputeResources:
        - Name: standard
          InstanceType: c5n.metal
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
      Networking:
        SubnetIds:
          - subnet-yyyy
        PlacementGroup:
          Enabled: true
          Id: cluster_placement
```

Removing `Enabled: true` from the `PlacementGroup` causes the file to throw an error from the `EfaPlacementGroupValidator`, but unsure if that is related, since that seems to be a legitimate error.

pcluster-cli.log:
```
2022-06-23 06:02:29,486 - INFO - entrypoint.py:226:run() - Handling CLI command create-cluster
```

Tested the config from both WSL and Ubuntu to confirm there wasn't some sort of OS related issue going on. 

Thanks
