### ISSUE TITLE
Feature Request: Local SharedStorage

### ISSUE THREAD

**Issue by ChristianKniep** [aws/aws-parallelcluster#4221]
When using a CustomAMI with a software repository installed it would be great to be able to share that without putting it into a dedicated EBS Volume.

Something along the lines of:
```yaml
SharedStorage:
  - Name: Spack Software
    MountDir: /spack
    StorageType: Local
    LocalSettings:
      SourcePath: /opt/spack
    
```

The above would export `/opt/spack` as `/spack` on all nodes (head node and compute node).
