### ISSUE TITLE
Mounted S3 bucket is not writeable by non-root (ubuntu) user

### ISSUE THREAD

**Issue by pradeeban** [aws/aws-parallelcluster#4273]
In AWS ParallelCluster version: 3.1.4, the S3 bucket that is mounted can be written only by the root user, and not by the non-root ubuntu user. Is this intentional? If so, how can I modify my configuration such that the MountDir Import/Export path directory (and its subdirectories) can be writeable by non-root (ubuntu) user? 

The full configuration is given below:
````
Region: us-east-2
Image:
  Os: ubuntu2004
  CustomAmi: ami-08ddea673d79b8450
HeadNode:
  InstanceType: t2.micro
  Networking:
    SubnetId: subnet-0ecabcbdfec66e462
  Ssh:
    KeyName: hummingbird
Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: queue1
    ComputeResources:
    - Name: t2micro
      InstanceType: t2.micro
      MinCount: 0
      MaxCount: 10
    Networking:
      SubnetIds:
      - subnet-0b670e56e895c5e57
SharedStorage:
  - MountDir: hummingbird
    Name: fsxhummingbird
    StorageType: FsxLustre
    FsxLustreSettings:
      StorageCapacity: 1200
      ExportPath: s3://cmat-thrust1/Marklein
      ImportPath: s3://cmat-thrust1/Marklein
````

The behavior can be seen by the below series of commands:
````
ubuntu@ip-10-0-2-78:/hummingbird$ touch test-test-123
ubuntu@ip-10-0-2-78:/hummingbird$ ls
Marklein  test-test-123
ubuntu@ip-10-0-2-78:/hummingbird$ cd Marklein/
ubuntu@ip-10-0-2-78:/hummingbird/Marklein$ touch test-test-456
touch: cannot touch 'test-test-456': Permission denied
ubuntu@ip-10-0-2-78:/hummingbird/Marklein$ sudo touch test-test-456
ubuntu@ip-10-0-2-78:/hummingbird/Marklein$ ls
Microglia_Morphology_Project  TS_GFCombo1  cellprofiler_logs  test-test-456
````

Am I missing something in the configuration?
