### ISSUE TITLE
Parallelcluster Job Stuck in CF While Compute Node Doesn't Do Anything

### ISSUE THREAD

**Issue by billflu** [aws/aws-parallelcluster#4373]
Hello,

I'm having an issue with running a Slurm job. I am following the instructions [here](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials-running-your-first-job-on-version-3.html#tutorial-1stjob-first-slurm-job) to submit a simple job. Slurm accepts the job and it shows in the queue, but there is no output. A compute node is spun up and remains in the CF (configuring) state, even though the node is accessible via ping and SSH. I can reach the compute node via IP or DNS name. I can also ping back from the compute node to the head node. Eventually the 30 minute timeout is hit and a new compute node is spun up (the old one is taken down). I've included the logs attached.

[test-cluster2-logs-202209231644.tar.gz](https://github.com/aws/aws-parallelcluster/files/9637037/test-cluster2-logs-202209231644.tar.gz)

Please let me know if you need anymore information. Thank you

**Required Info:**
 - AWS ParallelCluster version [e.g. 3.1.1]: 3.2.0
 - Full cluster configuration without any credentials or personal data:
```
Region: us-east-1
Image:
  Os: alinux2
HeadNode:
  InstanceType: t2.medium
  Networking:
    SubnetId: subnet-xxxxx
    ElasticIp: true
  Ssh:
    KeyName: blueprint
    AllowedIps: x.x.x.x/32
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: queue1
      Networking:
        SubnetIds:
          - subnet-xxxxx
        AssignPublicIp: false
      ComputeResources:
        - Name: compute-resource1
          InstanceType: m5.2xlarge
          MaxCount: 10
```
 - Cluster name: test-cluster2
 - Output of `pcluster describe-cluster` command.
 ```
{
  "creationTime": "2022-09-23T18:07:30.634Z",
  "headNode": {
    "launchTime": "2022-09-23T18:10:52.000Z",
    "instanceId": "i-0f37e8dd3c41e0de4",
    "publicIpAddress": "52.202.222.231",
    "instanceType": "t2.medium",
    "state": "running",
    "privateIpAddress": "172.17.5.60"
  },
  "version": "3.2.0",
  "clusterConfiguration": {
    "url": "https://parallelcluster-xxx-v1-do-not-delete.s3.amazonaws.com/parallelcluster/3.2.0/clusters/test-cluster2-p3fysbm322fosxmo/configs/cluster-config.yaml?versionId=boRF5jTx6xH_etMaiLvtsc4MIf2Zl7vO&AWSAccessKeyId=xxx&Signature=RyXhrEqKpj0g%2FuNDFCy7jbqI10s%3D&x-amz-security-token=xxx&Expires=1663967931"
  },
  "tags": [
    {
      "value": "3.2.0",
      "key": "parallelcluster:version"
    },
    {
      "value": "test-cluster2",
      "key": "parallelcluster:cluster-name"
    }
  ],
  "cloudFormationStackStatus": "CREATE_COMPLETE",
  "clusterName": "test-cluster2",
  "computeFleetStatus": "RUNNING",
  "cloudformationStackArn": "arn:aws:cloudformation:us-east-1:003681696602:stack/test-cluster2/xxx-3b6a-11ed-b0a9-123169bd2a8f",
  "lastUpdatedTime": "2022-09-23T18:07:30.634Z",
  "region": "us-east-1",
  "clusterStatus": "CREATE_COMPLETE",
  "scheduler": {
    "type": "slurm"
  }
}
```
 - [Optional] Arn of the cluster CloudFormation main stack:

**Bug description and how to reproduce:**
1. Create a cluster with the configuration above
2. Log in and create a simple [hellojob.sh](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials-running-your-first-job-on-version-3.html#tutorial-1stjob-first-slurm-job)
3. Submit the job `sbatch hellojob.sh`
4. Watch the job go into a CF (configuring) state and a compute node is spun up (note: the compute note does not have the logs requested)
5. The job hangs until it times out and a new compute node is launched
6. Rinse and repeat
