### ISSUE TITLE
mpirun fail to support background jobs according to scheduler description

### ISSUE THREAD

**Issue by steven-chien** [aws/aws-parallelcluster#4441]
- AWS ParallelCluster version: 3.2.1
 - Cluster description:
 ```yaml
Region: eu-north-1
Image:
  Os: ubuntu2004
HeadNode:
  InstanceType: t3.micro
  Networking:
    SubnetId: 
  Ssh:
    KeyName: EC2
  LocalStorage:
    RootVolume:
      VolumeType: gp2
      #Size: 35
Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: queue1
    CapacityType: SPOT
    ComputeResources:
    - Name: t3micro
      InstanceType: t3.micro
      MinCount: 0
      MaxCount: 2
      #Efa:
      #  Enabled: true
    ComputeSettings:
      LocalStorage:
        RootVolume:
          VolumeType: gp2
          Size: 35
    Networking:
      SubnetIds:
      - 
SharedStorage:
  - Name: FsxLustre0
    StorageType: FsxLustre
    MountDir: /pfs
    FsxLustreSettings:
      StorageCapacity: 6000
      DeploymentType: PERSISTENT_1
      StorageType: HDD
      DataCompressionType: LZ4
      PerUnitStorageThroughput: 12
```
 - Cluster name: HPC
 - Output of `pcluster describe-cluster` command:
 ```json
{
  "creationTime": "2022-10-17T10:59:17.461Z",
  "headNode": {
    "launchTime": "2022-10-17T11:07:56.000Z",
    "instanceType": "t3.micro",
    "state": "running",
  },
  "version": "3.2.1",
  "clusterConfiguration": {
  },
  "tags": [
    {
      "value": "3.2.1",
      "key": "parallelcluster:version"
    },
    {
      "value": "HPC",
      "key": "parallelcluster:cluster-name"
    }
  ],
  "cloudFormationStackStatus": "CREATE_COMPLETE",
  "clusterName": "HPC",
  "computeFleetStatus": "RUNNING",
  "lastUpdatedTime": "2022-10-17T10:59:17.461Z",
  "region": "eu-north-1",
  "clusterStatus": "CREATE_COMPLETE",
  "scheduler": {
    "type": "slurm"
  }
}
```
**Bug description and how to reproduce:**
I am trying to run two MPI programs (which are independent of each other) on the same cluster. I want one of them to have one process per node, and the second program to use the rest of the cores. In a properly configured HPC system with Slurm I would do the following:
```bash
# assume four nodes and two cores per node
srun -n 4 --ntasks-per-node=1 --cpu_bind=cores --exclusive ./a.out &
srun -n 4 --ntasks-per-node=1 --cpu_bind=cores --exclusive ./b.out
```
However, when I try to do the same with `mpirun`, the second program appears to be deadlocked while the first program can execute successfully.
```bash
# removing bind-to core does not fix the issue
mpirun -n 4 -npernode 1 --bind-to core ./a.out &
mpirun -n 4 -npernode 1 --bind-to core ./b.out
```
