### ISSUE TITLE
Shared Storage causes chef error

### ISSUE THREAD

**Issue by zcobell** [aws/aws-parallelcluster#4486]
### Cluster Configuration
```yaml
Region: us-east-2
Image:
  Os: alinux2
HeadNode:
  InstanceType: t3.micro
  Ssh:
    KeyName: key
  Networking:
    SubnetId: subnet-xxxx
  LocalStorage:
    RootVolume:
      VolumeType: gp3
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - Policy: arn:aws:iam::our/secret-manager-policy
  CustomActions:
    OnNodeConfigured:
      Script: >-
        https://raw.githubusercontent.com/aws-samples/pcluster-manager/main/resources/scripts/multi-runner.py
      Args:
        - >-
          https://raw.githubusercontent.com/aws-samples/pcluster-manager/main/resources/scripts/slurm-accounting.sh
        - >-
          -arn:secretmanager
        - '-database-endpoint'
        - '-3306'
DirectoryService:
  DomainName: dc=IJK,dc=XYZ,dc=org
  DomainAddr: ldap://XYZ
  PasswordSecretArn: >-
    ARNXYZ
  DomainReadOnlyUser: >-
    cn=ReadOnlyUser,ou=Users,ou=XYZ,
    dc=IJK,dc=XYZ,dc=org
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: o-hpc6a-096
      ComputeResources:
        - Name: o-hpc6a-096-hpc6a48xlarge
          MinCount: 0
          MaxCount: 20
          InstanceType: hpc6a.48xlarge
          Efa:
            Enabled: true
          DisableSimultaneousMultithreading: true
      Networking:
        SubnetIds:
          - subnet-xxxx
        PlacementGroup:
          Enabled: true
      ComputeSettings:
        LocalStorage:
          RootVolume:
            VolumeType: gp3
    - Name: s-c6a2x-002
      ComputeResources:
        - Name: s-c6a2x-002-c6axlarge
          MinCount: 0
          MaxCount: 10
          InstanceType: c6a.xlarge
          DisableSimultaneousMultithreading: true
      ComputeSettings:
        LocalStorage:
          RootVolume:
            VolumeType: gp3
      Networking:
        SubnetIds:
          - subnet-yyyy
      CapacityType: SPOT
SharedStorage:
  - Name: FsxLustre0
    StorageType: FsxLustre
    MountDir: /shared
    FsxLustreSettings:
      StorageCapacity: '2400'
      DeploymentType: SCRATCH_2
Tags:
  - Key: PROJECT_ID
    Value: XYZ
```

### Describe Cluster Output 

```json
{
  "creationTime": "2022-10-27T03:45:30.862Z",
  "headNode": {
    "launchTime": "2022-10-27T03:52:23.000Z",
    "instanceId": "i-0a30d03f389e013b0",
    "publicIpAddress": "[snip]",
    "instanceType": "t3.micro",
    "state": "running",
    "privateIpAddress": "10.0.0.221"
  },
  "version": "3.2.1",
  "clusterConfiguration": {
    "url": "[snip]"
  },
  "tags": [
    {
      "value": "3.2.1",
      "key": "parallelcluster:version"
    },
    {
      "value": "[snip]",
      "key": "parallelcluster:cluster-name"
    },
    {
      "value": "[snip]",
      "key": "PROJECT_ID"
    }
  ],
  "cloudFormationStackStatus": "CREATE_FAILED",
  "clusterName": "[snip]",
  "computeFleetStatus": "UNKNOWN",
  "cloudformationStackArn": "arn:aws:cloudformation:us-east-2:[snip]:stack/[snip]/cdab8f40-55a9-11ed-a6f6-0622e0c7f80e",
  "lastUpdatedTime": "2022-10-27T03:45:30.862Z",
  "region": "us-east-2",
  "clusterStatus": "CREATE_FAILED",
  "scheduler": {
    "type": "slurm"
  }
}
```

### Bug Description

Including a shared storage option in the above configuration causes chef to error during head node creation. Without this option, everything works fine. I've been able to reproduce the bug with FsxLustre and EFS. The log in cloudformation shows:

```
WaitCondition received failed message: 'Failed to run cfn-init. If --norollback was specified, check /var/log/cfn-init.log and /var/log/cloud-init-output.log.' for uniqueId: i-0053468e3142623f4
```

My best (uneducated) guess is that there was an update to chef via some initial update/install or an update to the scripts it grabs which is causing the issue.

[chef-client.log](https://github.com/aws/aws-parallelcluster/files/9875691/chef-client.log)
[cfn-init.log](https://github.com/aws/aws-parallelcluster/files/9875692/cfn-init.log)
[cloud-init.log](https://github.com/aws/aws-parallelcluster/files/9875693/cloud-init.log)

Thanks for your help
