### ISSUE TITLE
Creating cluster using PCM in ca-central-1 fails due to 

### ISSUE THREAD

**Issue by mendaomn** [aws/aws-parallelcluster#4529]
**Required Info:**
 - AWS ParallelCluster version [e.g. 3.1.1]: 3.3.0
 - Full cluster configuration without any credentials or personal data.

```
HeadNode:
  InstanceType: t2.micro
  Networking:
    SubnetId: subnet-024ead48239afeba2
  LocalStorage:
    RootVolume:
      VolumeType: gp3
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: queue0
      AllocationStrategy: lowest-price
      ComputeResources:
        - Name: queue0-compute-resource-0
          Instances:
            - InstanceType: c5n.large
          MinCount: 0
          MaxCount: 4
      Networking:
        SubnetIds:
          - subnet-024ead48239afeba2
      ComputeSettings:
        LocalStorage:
          RootVolume:
            VolumeType: gp3
  SlurmSettings: {}
Region: ca-central-1
Image:
  Os: alinux2
```

 - Cluster name: `test-cw`
 - Output of `pcluster describe-cluster` command.

**Bug description and how to reproduce:**
Creating a cluster in `ca-central-1` via PCM fails with  

```
User with accountId: XXX is not authorized to perform CreateLogGroup with Tags (Service: CloudWatchLogs, Status Code: 400, Request ID: 4c848ae1-5ff5-43dc-b67b-fd1a0f8cc33e)
```

**Additional context:**
- Cluster has been created via a PCM instance, installed on `ca-central-1`
- This comes from an issue opened against the PCM project https://github.com/aws-samples/pcluster-manager/issues/361
