### ISSUE TITLE
Feature Request: Support for Multi Regions

### ISSUE THREAD

**Issue by tkasuz** [aws/aws-parallelcluster#4919]
Currently we can configure multi AZ in a single queue by giving subnet ids, but it would be more helpful to support multi regions, which is connected by VPC Peering or Transit Gateway. My suggestion is like below

```yaml
Networking:
- Region: us-east-1
  SubnetIds:
  - subnet-0a4d8d435574ccfe5
```
