### ISSUE TITLE
DNS resolution not working on new 3.5.0 pcluster

### ISSUE THREAD

**Issue by hsimran13** [aws/aws-parallelcluster#4968]
Hello,

I just spun up a new 3.5.0 parallelcluster instance with the following configuration:

```
Region: us-east-1
Image:
  Os: centos7
  CustomAmi: ami-xxx
Tags:
  - Key: Application
    Value: 'POC ParallelCluster 3.5.0'
HeadNode:
  InstanceType: c5.xlarge
  Networking:
    SubnetId: subnet-xxx
    ElasticIp: false
  Ssh:
    KeyName: parallelcluster
  CustomActions:
    OnNodeConfigured:
      Script: s3://xxx/postscript
      Args:
        - poc
        - 01_adjoin.sh
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - Policy: arn:aws:iam:xxx:policy/pcluster-bucket-access
      - Policy: arn:aws:iam::xxx:policy/pcluster-secretsmgr-access
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    ScaledownIdletime: 20
  SlurmQueues:
    - Name: compute
      ComputeSettings:
        LocalStorage:
          EphemeralVolume:
            MountDir: local-scratch
      AllocationStrategy: lowest-price
      ComputeResources:
        - Name: comp1
          Instances:
          - InstanceType: c5.xlarge
          - InstanceType: c5d.xlarge
          MaxCount: 5
          Efa:
            Enabled: false
            GdrSupport: false
      CustomActions:
        OnNodeConfigured:
          Script: s3://xxx/postscript
          Args:
            - poc
            - 01_adjoin.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
          - Policy: arn:aws:iam::xxx:policy/pcluster-bucket-access
          - Policy: arn:aws:iam::xxx:policy/pcluster-secretsmgr-access
      Networking:
        SubnetIds:
          - subnet-xxx
```

The cluster is up and running and I see the private hosted zone has been created successfully.  I am able to run a sbatch job successfully without any issues but when I try to srun something or ping the compute node the DNS resolution fails:

```
$ srun hostname
srun: error: get_addr_info: getaddrinfo() failed: Name or service not known
srun: error: slurm_set_addr: Unable to resolve "compute-dy-comp1-1"
srun: error: fwd_tree_thread: can't find address for host compute-dy-comp1-1, check slurm.conf
srun: error: Task launch for StepId=4.0 failed on node compute-dy-comp1-1: Can't find an address, check slurm.conf
srun: error: Application launch failed: Can't find an address, check slurm.conf
srun: Job step aborted
```

I am unable to resolve compute-dy-comp1-1 manually as well:

```
$ sinfo -lNe
Tue Feb 28 02:33:55 2023
NODELIST            NODES PARTITION       STATE CPUS    S:C:T MEMORY TMP_DISK WEIGHT AVAIL_FE REASON
compute-dy-comp1-1      1  compute*        idle 4       4:1:1   7782        0      1 dynamic, none
compute-dy-comp1-2      1  compute*       idle~ 4       4:1:1   7782        0      1 dynamic, none
compute-dy-comp1-3      1  compute*       idle~ 4       4:1:1   7782        0      1 dynamic, none
compute-dy-comp1-4      1  compute*       idle~ 4       4:1:1   7782        0      1 dynamic, none
compute-dy-comp1-5      1  compute*       idle~ 4       4:1:1   7782        0      1 dynamic, none
$ ping compute-dy-comp1-1
ping: compute-dy-comp1-1: Name or service not known
```

Is there something I need to do in order to get Route53 to work properly from the master/compute nodes?  Any help would be greatly appreciated.

Thanks,
-Simran
