### ISSUE TITLE
EFS config sanity failure

### ISSUE THREAD

**Issue by blakemertz** [aws/aws-parallelcluster#5040]
**Required Info:**
 - AWS ParallelCluster version: 3.5.0
 - Full cluster configuration:
```
Region: us-east-1
Image:
  Os: centos7
HeadNode:
  InstanceType: m5.2xlarge
  Networking:
    SubnetId: subnet-08a5acdaf486f2e6d
  Ssh:
    KeyName: mertz_key
Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: modbind
    ComputeResources:
    - Name: g4dnmetal
      Instances:
      - InstanceType: g4dn.metal
      MinCount: 0
      MaxCount: 1
      Efa:
        Enabled: true
    Networking:
      PlacementGroup:
        Enabled: true
      SubnetIds:
      - subnet-08a5acdaf486f2e6d
SharedStorage:
    - MountDir: /data/modstore1
      Name: modstore1
      StorageType: Efs
      EfsSettings:
        FileSystemId: fs-xxxxxxxx
```
 - Cluster name: modbind-noAD-modstore1
 - Output of `pcluster describe-cluster` command:
```
pcluster describe-cluster -n modbind-noAD-modstore1
{
  "message": "Cluster 'modbind-noAD-modstore1' does not exist or belongs to an incompatible ParallelCluster major version."
}
```
 - [Optional] Arn of the cluster CloudFormation main stack:
(https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/stackinfo?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A271013678229%3Astack%2Fparallelclusternetworking-pub-20230309164455%2Fd0ef4990-be99-11ed-b5ad-1235826a783b)

**Bug description and how to reproduce:**
I am attempting to create a cluster with shared EFS storage. Upon checking the security group settings, cluster creation spits the bit:
```
pcluster create-cluster -n modbind-noAD-modstore1 -c modbind-noAD-modstore1.yaml 
{
  "configurationValidationErrors": [
    {
      "level": "ERROR",
      "type": "EfsIdValidator",
      "message": "There is an existing Mount Target fsmt-f1ddf1b8 in the Availability Zone us-east-1c for EFS fs-c3e2bb8a, but it does not have a security group that allows inbound and outbound rules to support NFS. Please modify the Mount Target's security group, to allow traffic on port 2049."
    },
    {
      "level": "WARNING",
      "type": "EfsIdValidator",
      "message": "There is an existing Mount Target fsmt-f1ddf1b8 in the Availability Zone us-east-1c for EFS fs-c3e2bb8a, but it does not have a security group that allows inbound and outbound rules to allow traffic of subnet subnet-08a5acdaf486f2e6d. Please modify the Mount Target's security group, to allow traffic on subnet."
    }
  ],
  "message": "Invalid cluster configuration."
}
```
As far as I can tell, the NFS on our EFS is already set to be open to port 2049 (see attached image), so it's not clear to me why I am getting this error message when trying to create the cluster.
![efs-nfs](https://user-images.githubusercontent.com/44912632/224166932-4d8c51fd-5d1d-402b-b6e3-a304d63846a6.png)

**If you are reporting issues about cluster creation failure or node failure:**

If the cluster fails creation, please re-execute `create-cluster` action using `--rollback-on-failure false` option.

Since the cluster wasn't created, nothing to describe here. Can't provide log files from the head/compute node either. I'm attaching my parallelcluster.cli log file as well. It appears related to the same issue that was reported for earlier versions of v3. of PC, but that issue was never resolved from what I can tell: (https://github.com/aws/aws-parallelcluster/issues/997)
[pcluster-cli.log](https://github.com/aws/aws-parallelcluster/files/10936136/pcluster-cli.log)

**Comment by enrico-usai** [comment]
Hi @blakemertz 

If you're sure the security group is correct, to unblock the cluster creation, you can execute:
```
pcluster create-cluster ... --suppress-validators type:EfsIdValidator
```

Anyway I think the key is in the error message:
```
"There is an existing Mount Target fsmt-f1ddf1b8 in the Availability Zone us-east-1c for EFS fs-c3e2bb8a, but it does not have a security group that allows inbound and outbound rules to allow traffic of subnet subnet-08a5acdaf486f2e6d. Please modify the Mount Target's security group, to allow traffic on subnet.
```

You're using for the cluster the subnet `subnet-08a5acdaf486f2e6d` and the security group associated to the Mount Target of your EFS don't permit communications with this subnet. You can check detailed instructions in the [official doc](https://docs.aws.amazon.com/parallelcluster/latest/ug/SharedStorage-v3.html#yaml-SharedStorage-EfsSettings-FileSystemId). 

An alternative is to pass the Mount Target security group as `AdditionalSecurityGroups` configuration parameter, for both the [head node](https://docs.aws.amazon.com/parallelcluster/latest/ug/HeadNode-v3.html#yaml-HeadNode-Networking-AdditionalSecurityGroups) and the [queue nodes](https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmQueues-Networking-AdditionalSecurityGroups).

Let us know if it helps.

**Comment by blakemertz** [comment]
@enrico-usai thanks for catching that detail with the mismatched subnets between our EFS drive the the parallelcluster I was trying to create. After switching it to the correct subnet, it finally worked! I had to use parallelcluster-UI to generate the correct configuration file, so will need to go back and debug why I was still unsuccessful in generating the cluster from the CLI, but all of our EFS files/folders are showing up in the cluster I created.

For any future users that need to reference my configuration script, it is below:
```
HeadNode:
  InstanceType: c5.2xlarge
  Networking:
    SubnetId: subnet-xxxxxxxx
    AdditionalSecurityGroups:
      - sg-xxxxxxxx
  Ssh:
    KeyName: mertz_key
  LocalStorage:
    RootVolume:
      VolumeType: gp3
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: modbind
      AllocationStrategy: lowest-price
      ComputeResources:
        - Name: modbind-compute
          Instances:
            - InstanceType: g4dn.metal
          MinCount: 0
          MaxCount: 10
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
      Networking:
        SubnetIds:
          - subnet-xxxxxxxx
        PlacementGroup:
          Enabled: true
        AdditionalSecurityGroups:
          - sg-xxxxxxxx
      ComputeSettings:
        LocalStorage:
          RootVolume:
            VolumeType: gp3
    - Name: spot
      AllocationStrategy: lowest-price
      ComputeResources:
        - Name: spot-compute
          Instances:
            - InstanceType: g4dn.metal
          MinCount: 0
          MaxCount: 10
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
      Networking:
        SubnetIds:
          - subnet-xxxxxxxx
        PlacementGroup:
          Enabled: true
        AdditionalSecurityGroups:
          - sg-xxxxxxxx
      ComputeSettings:
        LocalStorage:
          RootVolume:
            VolumeType: gp3
    - Name: spot
      AllocationStrategy: lowest-price
      ComputeResources:
        - Name: spot-compute
          Instances:
            - InstanceType: g4dn.metal
          MinCount: 0
          MaxCount: 10
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
      ComputeSettings:
        LocalStorage:
          RootVolume:
            VolumeType: gp3
      CapacityType: SPOT
      Networking:
        SubnetIds:
          - subnet-xxxxxxxx
        PlacementGroup:
          Enabled: true
        AdditionalSecurityGroups:
          - sg-xxxxxxxx
  SlurmSettings: {}
Region: us-east-1
Image:
  Os: centos7
SharedStorage:
  - Name: modstore1
    StorageType: Efs
    MountDir: /shared
    EfsSettings:
      FileSystemId: fs-xxxxxxxx
```
