### ISSUE TITLE
Using DLAMI: Could not get IMDSv2 token. Instance Metadata might have been disabled or this is not an EC2 instance

### ISSUE THREAD

**Issue by lipovsek-aws** [aws/aws-parallelcluster#5100]
**Required Info:**
 - AWS ParallelCluster version [e.g. 3.1.1]: 3.3
 - I'm using `pcluster build-image` so cluster config is not relevant. Here is build image config:
 ```
Build:
  SecurityGroupIds: [sg-1]
  SubnetId: subnet-2
  InstanceType: g5.2xlarge
  ParentImage: ami-0d08c00fae325064c # DLAMI in us-east-1
```

**Bug description and how to reproduce:**
I would like to use DLAMI (Deep Learning AMI GPU PyTorch 1.13.1 (Ubuntu 20.04) 20230315) on pcluster. Variant of this issue is [already known](https://github.com/aws/aws-parallelcluster/wiki/(3.3.0-3.4.1)-Custom-AMI-creation-fails-on-Ubuntu-20.04-during-MySQL-packages-installation), but I'm getting "Could not get IMDSv2 token. Instance Metadata might have been disabled or this is not an EC2 instance" error in EC2 Image Builder logs ([log-events-viewer-result.csv](https://github.com/aws/aws-parallelcluster/files/11019764/log-events-viewer-result.4.csv)).
This is fixed by upgrading pcluster version to 3.5 . This issue is probably not limited to DLAMI.
