### ISSUE TITLE
secret ARN validation warning

### ISSUE THREAD

**Issue by blakemertz** [aws/aws-parallelcluster#5135]
I'm trying to generate a cluster with 1) microsoft active directory for multiple users and 2) shared EFS partition for convenience of storing big data to our virtual drive. I have managed to accomplish #2, and also have managed to create a microsoft AD. However, when I did a dry run in the ParallelCluster UI, I get the following warning:
```
ValidationWarnings:
PasswordSecretArnValidator: Cannot validate secret arn:aws:secretsmanager:us-east-1:XXXXXXXXXXXX:secret:PasswordSecret-modulus-AD-XXXXXX due to lack of permissions. Please refer to ParallelCluster official documentation for more information.
```
I will still be able to create the cluster, but I want to know where I can properly locate my secret ARN for the microsoft AD? I thought I had properly copied it from my cloud formation console:
![image](https://user-images.githubusercontent.com/44912632/228327713-14da421c-90d0-492e-9191-0707e738945b.png)
but then I wouldn't be getting that validation warning, correct? Is there a different ARN that I should be referencing? The only other possibility I can see is DomainCertificateSecretArn or DomainCertificateSecretReadPolicy.

Below is my configuration script:
```
HeadNode:
  InstanceType: c5.2xlarge
  Networking:
    SubnetId: subnet-xxxxxxxx
    AdditionalSecurityGroups:
      - sg-xxxxxxxx
  Ssh:
    KeyName: mertz_key
  LocalStorage:
    RootVolume:
      VolumeType: gp3
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: modbind
      AllocationStrategy: lowest-price
      ComputeResources:
        - Name: modbind
          Instances:
            - InstanceType: g4dn.metal
          MinCount: 0
          MaxCount: 10
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
      Networking:
        SubnetIds:
          - subnet-xxxxxxxx
        PlacementGroup:
          Enabled: true
        AdditionalSecurityGroups:
          - sg-xxxxxxxx
      ComputeSettings:
        LocalStorage:
          RootVolume:
            VolumeType: gp3
      CustomActions:
        OnNodeConfigured:
          Script: >-
            s3://parallelcluster-10552b48cfa2e9aa-v1-do-not-delete/modbind-cluster-setup.sh
    - Name: spot
      AllocationStrategy: lowest-price
      ComputeResources:
        - Name: spot
          Instances:
            - InstanceType: g4dn.metal
          MinCount: 0
          MaxCount: 10
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
      ComputeSettings:
        LocalStorage:
          RootVolume:
            VolumeType: gp3
      CapacityType: SPOT
      Networking:
        SubnetIds:
          - subnet-xxxxxxx
        PlacementGroup:
          Enabled: true
        AdditionalSecurityGroups:
          - sg-xxxxxxx
      CustomActions:
        OnNodeConfigured:
          Script: >-
            s3://parallelcluster-10552b48cfa2e9aa-v1-do-not-delete/modbind-cluster-setup.sh
  SlurmSettings: {}
Region: us-east-1
Image:
  Os: centos7
DirectoryService:
  DomainName: modulus.ad.com
  DomainAddr: ldaps://modulus.ad.com
  PasswordSecretArn: >-
    arn:aws:secretsmanager:us-east-1:xxxxxxxxxxxx:secret:PasswordSecret-modulus-AD-xxxxxx
  DomainReadOnlyUser: cn=ReadOnlyUser,ou=Users,ou=MODULUS,dc=modulus,dc=ad,dc=com
SharedStorage:
  - Name: Efs0
    StorageType: Efs
    MountDir: /shared
    EfsSettings:
      FileSystemId: fs-xxxxxxxx
```
