### ISSUE TITLE
DirectoryService secrets manager ARN processing breaks on valid secret ARN   ##DELETE THIS##

### ISSUE THREAD

**Issue by chrisdag** [aws/aws-parallelcluster#5137]
Summary:

Parallelcluster 3.5.0 will accept slurmdb secret arn names where the secret contains "/" characters like "/prod/hpc/slurmdb" but the same ARN pattern used in the DirectoryServices section results in a python parsing error. Changing the ldap secret name to remove "/" characters resolves the problem. 
 
** How to reproduce **

This breaks on pcluster 3.5.0:

````
DirectoryService:
  DomainName: DC=aadds,DC=company,DC=com
  DomainAddr: ldaps://ad1.aadds.company.com:636,ldaps://ad1.aadds.company.com:636
  LdapTlsReqCert: demand
  PasswordSecretArn: arn:aws:secretsmanager:us-east-1:XXXXXXX:secret:company/prod/ldapserviceaccount-ZMROCn
  DomainReadOnlyUser: svc_aaddsauth@aadds.company.com
  GenerateSshKeysForUsers: true
  AdditionalSssdConfigs:
    ldap_search_base: OU=AADDC Users,DC=aadds,DC=company,DC=com
    override_homedir: /efs/home/%u
    override_shell:  /usr/bin/bash
```` 

Validation and dryrun=true  passes but deploy cluster generates this error

````
{
  "configurationValidationErrors": [
    {
      "level": "ERROR",
      "type": "PasswordSecretArnValidator",
      "message": "type of argument resource must be str; got NoneType instead"
    }
  ],
  "message": "Invalid cluster configuration."
}
````

This works on pcluster 3.5.0 -- all we had to do was simplify the ad user secret name so the ARN secret name does not have "/" values in it:

````
DirectoryService:
  DomainName: DC=aadds,DC=company,DC=com
  DomainAddr: ldaps://ad1.aadds.company.com:636,ldaps://ad1.company.company.com:636
  LdapTlsReqCert: demand
  PasswordSecretArn: arn:aws:secretsmanager:us-east-1:XXXX:secret:aads-ldap-HA1kII
  DomainReadOnlyUser: svc_aaddsauth@aadds.company.com
  GenerateSshKeysForUsers: true
  AdditionalSssdConfigs:
    ldap_search_base: OU=AADDC Users,DC=aadds,DC=company,DC=com
    override_homedir: /efs/home/%u
    override_shell:  /usr/bin/bash
````
  

**Required Info:**
 - AWS ParallelCluster version [e.g. 3.1.1]:  3.5.0

** Cluster Config ** 

````
Region: us-east-1
Image:
  Os: ubuntu2004
HeadNode:
  InstanceType: t3.large
  Networking:
    SubnetId: subnet-06b367161adc09e13
    AdditionalSecurityGroups:
      - sg-0d0b2a5c4d6048e66
      - sg-05cb38c5fba7a7385
  Ssh:
    KeyName: company-prod-opskey-01
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::XXXX:policy/scicomp-hpc-automation-enablement
  CustomActions:
    OnNodeStart:
      Script: s3://company-prod-bootstrap-automation/pcluster/3.5.0/dns-and-ssl-tweak.sh
    OnNodeConfigured:
      Script: s3://company-prod-bootstrap-automation/pcluster/3.5.0/ubuntu-bootstrap-pcluster-via-ansible-git-pull-v1.sh
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    Database:
      Uri: slurm-hpc-job-accounting-nonha.cuqybyhbdaun.us-east-1.rds.amazonaws.com:3306
      UserName: slurm
      PasswordSecretArn: arn:aws:secretsmanager:us-east-1:XXX:secret:company/prod/slurmdb-nT1mvk
  SlurmQueues:
  - Name: cpu-q
    ComputeResources:
    - Name: c6i-2xlarge
      InstanceType: c6i.2xlarge
      MinCount: 0
      MaxCount: 10
    Networking:
      SubnetIds:
      - subnet-06b367161adc09e13
      AdditionalSecurityGroups:
      - sg-0d0b2a5c4d6048e66
    CustomActions:
      OnNodeStart:
        Script: s3://company-prod-bootstrap-automation/pcluster/3.5.0/dns-and-ssl-tweak.sh
      OnNodeConfigured:
        Script: s3://company-prod-bootstrap-automation/pcluster/3.5.0/ubuntu-bootstrap-pcluster-via-ansible-git-pull-v1.sh
    Iam:
      AdditionalIamPolicies:
        - Policy: arn:aws:iam::XXX:policy/scicomp-hpc-automation-enablement
SharedStorage:
  - MountDir: /efs
    Name: company-scicomp-efs
    StorageType: Efs
    EfsSettings:
      FileSystemId: fs-0f21a0d79182ce74e
Monitoring:
  DetailedMonitoring: false
  Logs:
    CloudWatch:
      Enabled: true
      RetentionInDays: 14
      DeletionPolicy: Delete
  Dashboards:
    CloudWatch:
      Enabled: true
DirectoryService:
  DomainName: DC=aadds,DC=company,DC=com
  DomainAddr: ldaps://ad1.aadds.company.com:636,ldaps://ad1.aadds.company.com:636
  LdapTlsReqCert: demand
  PasswordSecretArn: arn:aws:secretsmanager:us-east-1:XXXX:secret:company/prod/ldapserviceaccount-ZMROCn
  DomainReadOnlyUser: svc_aaddsauth@aadds.company.com
  GenerateSshKeysForUsers: true
  AdditionalSssdConfigs:
    ldap_search_base: OU=AADDC Users,DC=aadds,DC=company,DC=com
    override_homedir: /efs/home/%u
    override_shell:  /usr/bin/bash
Tags:
  - Key: 'Platform'
    Value: 'HPC'
  - Key: 'Project'
    Value: 'Scientific Computing'
  - Key: 'Description'
    Value: 'Auto-scaling HPC cluster environment'
  - Key: 'Contact'
    Value: 'Chris Dagdigian'
````

**Bug description and how to reproduce:**

See above.
