### ISSUE TITLE
New security groups are created even though Networking->SecurityGroups of HeadNode and all queues and EFS mount target has the same security group and the EFS is created beforehand

### ISSUE THREAD

**Issue by mopk** [aws/aws-parallelcluster#5232]
Hello,
I want' to avoid creation of any new security groups. The ones created by Parallel Cluster v3.5.0 I currently use are like all allowed within them and thus duplicating my existing security group I want to use.

My config is:
```
Region: <my-region>
Image:
  CustomAmi: <my-ami-id>
  Os: <my-ami-os>
SharedStorage:
  - MountDir: <my-mount-dir-path>
    Name: my-efs-mount
    StorageType: Efs
    EfsSettings:
      FileSystemId: <my-efs-file-system-id>
HeadNode:
  Imds:
    Secured: false
  InstanceType: <my-instance-type>
  Networking:
    SubnetId: <my-subnet-id>
    SecurityGroups:
      - <my-security-group-id>
  Ssh:
    KeyName: <my-key>
  LocalStorage:
    RootVolume:
      Size: 50
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    ScaledownIdletime: 5
  SlurmQueues:
    - Name: queue1
      ComputeResources:
        - Name: <compute-resource-name>
          InstanceType: <my-instance-type>
      Networking:
        SubnetIds:
          - <my-subnet-id>
        SecurityGroups:
          - <my-security-group-id>
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 50
```

My EFS file system is created beforehand and its mount target has the same subnet and security group as the HeadNode and queue.
(They are all in the same VPC, region, availability zone.)

NOTE: The problem doesn't happen with an FSx Lustre file system created beforehand.

Is there any explicit flag/option to make pcluster CLI avoid creation of any new SGs?
I expect that creation is to be avoided when I set my existing SG to Head Node and all the queues as per documentation.
But by some unclear to me reason this doesn't happen as expected. For now the behaviour when one creates an EFS beforehand and use the same groups for its mount target, HeadNode and all queues and pcluster creates new security groups looks like a bug.
