### ISSUE TITLE
3.4.1: Spot requests remain untagged. 

### ISSUE THREAD

**Issue by francisreyes-tfs** [aws/aws-parallelcluster#5288]
In an effort to be vigilant with tagging, in 3.4.1, when CapacityType = SPOT, the spot requests themselves do not show tags despite Tags: being defined in the parallelcluster configuration.

**Comment by francesco-giordano** [comment]
Hi francisreyes-tfs,
just to clarify the issue with ParallelCluster version 3.4.1, with a configuration like the following, do you not find the `Tags` `test-spot` in your compute node instance tag? 
```
Region: eu-west-1
Tags:
  - Key: test-spot
    Value: test-spot
Image:
  Os: alinux2
HeadNode:
  InstanceType: c5.large
  Networking:
    SubnetId: subnet-xxxxxxxxxxxxxxxxx
  Ssh:
    KeyName: <YOUR_KEY>
Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: queue1
    CapacityType: SPOT
    ComputeResources:
    - Name: c5large
      InstanceType: c5.large
      MinCount: 1
      MaxCount: 4
    Networking:
      SubnetIds:
      - subnet-xxxxxxxxxxxxxxxxx
```
