### ISSUE TITLE
Feature Request: AutoExportPolicy for Lustre

### ISSUE THREAD

**Issue by miikkahoo** [aws/aws-parallelcluster#5406]
When creating an Fsx for Lustre, there is no option to configure an auto export policy. It needs to be done when the association with S3 is done, it cannot be added afterwards.
I have an use case where output files would need to be downloaded from AWS for post-processing. Currently Export from Lustre to S3 needs to be done manually which could be automated.

Something like this would be awesome:
```yaml
SharedStorage:
  - StorageType: FsxLustre
  - FsxLustreSettings:
    AutoImportPolicy: NEW_CHANGED_DELETED
    AutoExportPolicy: NEW_CHANGED
```
