### ISSUE TITLE
Login Nodes Feature does not set `Tags:` 

### ISSUE THREAD

**Issue by michaelmayer2** [aws/aws-parallelcluster#5790]
When using `Tags:` and `LoginNodes` in the same cluster environment, the login node creation and as a consequence the whole cluster will fail s the launch template for the Login Nodes reports "Permission denied". 

This happens on an AWS account where the presence of tags is enforced. 

Tested with AWS ParallelCluster 3.7.2

Workaround: Disable automatic rollback and manually edit Launch template for Login Node creation in order to add the requested Tags there, then retry the creation of the full stack. This time it will succeed. 

Sample template file below. 

```
Region: eu-west-1
Image:
  Os: alinux2
HeadNode:
  InstanceType: t2.micro
  Networking:
    SubnetId: subnet-xyz
  Ssh:
    KeyName: michael
Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: queue1
    ComputeResources:
    - Name: t2micro
      Instances:
      - InstanceType: t2.micro
      MinCount: 0
      MaxCount: 10
    Networking:
      SubnetIds:
      - subnet-xyz

LoginNodes:
  Pools:
    - Name: login
      Count: 1 
      InstanceType: t2.xlarge
      Networking:
        SubnetIds: 
          - subnet-xyz

Tags:
  - Key: rs:environment
    Value: development
  - Key: rs:project
    Value: solutions
```
