### ISSUE TITLE
Feature Request: Support for Security Groups in FSX Lustre Settings

### ISSUE THREAD

**Issue by sheppard-brandon-bah** [aws/aws-parallelcluster#5818]
**Required Info:**
 - AWS ParallelCluster version 3.7.2

I am blocked from using the Parallel Cluster CLI in enterprise-provided AWS accounts and in most of the government-provided AWS accounts I have encountered due to the creation of the FSX Cluster Security Group and Security Group Rules that are part of the FSX Lustre Cluster deployment. Due to security restrictions in place on these types of accounts, account-level IAM users are blocked from creating their our own Security Groups and Rules. Instead, a set of standard groups/rules are provided for each account.

In order to enable use of the Parallel Cluster CLI within enterprise and government AWS environments, can we please have the option to configure existing Security Groups to be used in the FSX Lustre Cluster deployment over forcing the creation of a new group with no option to add one?

An example config snippet below...

```
  SharedStorage:
    MountDir: /workspace
    Name: fsx-workspace
    StorageType: FsxLustre
    FsxLustreSettings:
      StorageCapacity: 1200
      ImportedFileChunkSize: 1024
      ExportPath: s3://pcluster-training-workspace
      ImportPath: s3://pcluster-training-workspace
      SecurityGroupIds: 
         - sg-xxxxx
         - sg-xxxxx
```
