### ISSUE TITLE
Unable to create new pcluster AMI

### ISSUE THREAD

**Issue by jagga13** [aws/aws-parallelcluster#6358]
Hello,

I am trying to create a new parallel cluster AMI based on a custom AMI.  This process seems to keep failing even though I have granted it full IAM access to S3/KMS/SSM.  Here are the details:

AWS ParallelCluster version 3.10.1

Image config:
```
Region: us-west-2
Build:
  InstanceType: c5.xlarge
  ParentImage: ami-XXXXX
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::{xxxxxxx}:policy/kms-full-access
      - Policy: arn:aws:iam::aws:policy/AmazonS3FullAccess
      - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
  SecurityGroupIds:
    - sg-XXXXX
  SubnetId: subnet-XXXXX
  UpdateOsPackages:
    Enabled: false
```

I see the following errors in CloudFormation:

```
The following resource(s) failed to create: [ParallelClusterImage]. 
Resource handler returned message: "Error occurred during operation 'Workflow Execution ID: 'wf-b867ea03-6bf2-4910-a834-a548aa0728d2' failed with reason: Unable to bootstrap TOE'." (RequestToken: 395ac732-4b6b-1535-c8a3-b3c7413fa788, HandlerErrorCode: GeneralServiceException)
```

I see the following errors in CloudWatch:

```
Started step ApplyBuildComponents with action ExecuteComponents
Sending command to instance to run
Running command (command id: 3ec02c84-29d5-444d-9cb1-a639c91ac362)
Waiting for command to complete (command id: 3ec02c84-29d5-444d-9cb1-a639c91ac362). Attempt number: 1.
Command failed (command id: 3ec02c84-29d5-444d-9cb1-a639c91ac362, state: Failed)
```

The ec2 builder instance seems to come up in a healthy state but is terminated after this above failed step and I can't disable rollback on failure either by passing in the option since it might be too early in the build process.  Any help would be appreciated!

Thanks!
