### ISSUE TITLE
Image Building on Pcluster 3.9.3/3.9.2

### ISSUE THREAD

**Issue by QuintenSchrevens** [aws/aws-parallelcluster#6390]
so trying to build a custom image on 3.9.2 or 3.9.3 errors in the same exact way this error was not there before, might have something todo with a cookbook change. this error happens in the first phase of building the image.

have confirmed this issue is not there when using 3.10.1 but I need to use 3.9.3/3.9.2 for my specific use case. 

**Required Info:**
 - AWS ParallelCluster version: 3.9.3
 - Using ParallelCluster official amazon linux 2 AMI 

**Bug description and how to reproduce:**
`Pcluster build-image -i <name> -c <config.yml>`

pcluster image build config:

```
Region: <region>
Image:
  Name: <name>
  Tags:
    - Key: Name
      Value:  <name>
    - Key: Version
      Value: 1.0.0
  RootVolume:
    Size: 200
    Encrypted: True
Build:
  Imds:
    ImdsSupport: v2.0
  InstanceType: g5.xlarge 
  ParentImage: ami-0e9887bc24117c02e
  SecurityGroupIds:
    - <sg-id>
  SubnetId: <subnet id>
  Iam:
    AdditionalIamPolicies:
      - Policy: <policy>
  Components:
    - Type: arn
      Value: arn:aws:imagebuilder:eu-west-1:aws:component/amazon-cloudwatch-agent-linux/x.x.x
    - Type: arn
      Value: <other custom components>
```

AWS image builder logs:

```
CmdExecution: Stderr: mkdir -p /etc/chef && sudo chown -R root:root /etc/chef
curl --retry 3 -L -o /etc/chef/aws-parallelcluster-cookbook.tgz "https://eu-west-1-aws-parallelcluster.s3.eu-west-1.amazonaws.com/parallelcluster/3.9.2/cookbooks/aws-parallelcluster-cookbook-3.9.2.tgz"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  589k  100  589k    0     0  6453k      0 --:--:-- --:--:-- --:--:-- 6474k

mkdir /tmp/cookbooks
cd /tmp/cookbooks
tar -xzf /etc/chef/aws-parallelcluster-cookbook.tgz

export HOME="/tmp"
for dir in $(ls /tmp/cookbooks); do
  cd /tmp/cookbooks/${dir}
  LANG=en_US.UTF-8 sudo /opt/cinc/embedded/bin/berks vendor /etc/chef/cookbooks --delete || (echo 'Vendoring cookbook failed.' && exit 1)
done;
<internal:/opt/cinc/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- archive/tar/minitar (LoadError)
	from <internal:/opt/cinc/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/berkshelf-8.0.7/lib/berkshelf/packager.rb:1:in `<top (required)>'
	from /opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/berkshelf-8.0.7/lib/berkshelf/berksfile.rb:1:in `require_relative'
	from /opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/berkshelf-8.0.7/lib/berkshelf/berksfile.rb:1:in `<top (required)>'
	from /opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/berkshelf-8.0.7/lib/berkshelf.rb:222:in `require_relative'
	from /opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/berkshelf-8.0.7/lib/berkshelf.rb:222:in `<top (required)>'
	from /opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/berkshelf-8.0.7/lib/berkshelf/cli.rb:1:in `require_relative'
	from /opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/berkshelf-8.0.7/lib/berkshelf/cli.rb:1:in `<top (required)>'
	from <internal:/opt/cinc/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/cinc/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/berkshelf-8.0.7/bin/berks:3:in `<top (required)>'
	from /opt/cinc/embedded/bin/berks:25:in `load'
	from /opt/cinc/embedded/bin/berks:25:in `<main>'
```
