### ISSUE TITLE
Maybe some bugs I have met

### ISSUE THREAD

**Issue by wbadyx** [aws/aws-parallelcluster#6393]
I have created the cluster several times following the documentation, but I have not succeeded.

pcluster version: 3.10.1

**create cluster cmd:**
```
pcluster create-cluster --cluster-name awspc --cluster-configuration config-file.yaml
```
**config-file.yaml**
```
Imds:
  ImdsSupport: v2.0
HeadNode:
  InstanceType: m6i.large
  Imds:
    Secured: true
  Ssh:
    KeyName: EC2-Global
  LocalStorage:
    RootVolume:
      VolumeType: gp3
  Networking:
    SubnetId: subnet-0cc9c0663cfc28aa3
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  Dcv:
    Enabled: true
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: queue-1
      AllocationStrategy: lowest-price
      ComputeResources:
        - Name: queue-1-cr-1
          Instances:
            - InstanceType: c5n.large
          MinCount: 1
          MaxCount: 5
      ComputeSettings:
        LocalStorage:
          RootVolume:
            VolumeType: gp3
      Networking:
        SubnetIds:
          - subnet-0cc9c0663cfc28aa3
    - Name: queue-2
      AllocationStrategy: lowest-price
      ComputeResources:
        - Name: queue-2-cr-1
          Instances:
            - InstanceType: c6i.large
          MinCount: 1
          MaxCount: 11
        - Name: queue-2-cr-2
          Instances:
            - InstanceType: c5n.large
          MinCount: 0
          MaxCount: 4
      ComputeSettings:
        LocalStorage:
          RootVolume:
            VolumeType: gp3
      Networking:
        SubnetIds:
          - subnet-0cc9c0663cfc28aa3
        PlacementGroup:
          Enabled: true
      CapacityType: SPOT
  SlurmSettings: {}
Region: us-east-1
Image:
  Os: alinux2
SharedStorage:
  - Name: Efs0
    StorageType: Efs
    MountDir: /shared
    EfsSettings:
      ThroughputMode: bursting
      DeletionPolicy: Delete
Tags:
  - Key: parallelcluster-v3
    Value: 'true'
Monitoring:
  DetailedMonitoring: false
  Logs:
   CloudWatch:
     Enabled: true
     RetentionInDays: 7
     DeletionPolicy: Delete
  Dashboards:
   CloudWatch:
     Enabled: true

```

**The CloudFormation Issue:**

![微信截图_20240814163121](https://github.com/user-attachments/assets/4ac56c46-990e-4442-b4a6-3d81a093dc8c)
