### ISSUE TITLE
Slurmqueue naming validation errors

### ISSUE THREAD

**Issue by QuintenSchrevens** [aws/aws-parallelcluster#6548]
**Issue: Error when using hyphens in SlurmQueue names**

### AWS ParallelCluster Version
- Tested on versions: 3.10 & 3.11

### Description
When configuring a cluster with hyphens in the `SlurmQueue` names, the following error occurs:

**Example Configuration snippet:**
```yaml
SlurmQueues:
  - Name: a10-medium
    JobExclusiveAllocation: true
    ComputeResources:
      - Name: a10-medium
        InstanceType: g5.12xlarge
        MinCount: 0
        MaxCount: 4
        Efa:
          Enabled: true
```

### Error Message
```json
{
  "configurationValidationErrors": [
    {
      "level": "ERROR",
      "type": "NameValidator",
      "message": "Invalid name 'a10-medium'. Name must begin with a letter and only contain lowercase letters, digits and hyphens."
    }
  ]
}
```

### Expected Behavior
The configuration should allow hyphens in `SlurmQueue` names without producing a validation error.

### Steps to Reproduce
1. Define a cluster configuration with a `SlurmQueue` name that includes hyphens (e.g., `a10-medium`).
2. Attempt to create the cluster.

### Request
Is there any plan to adjust the validation rules to allow hyphens in `SlurmQueue` names, or should I follow a different naming convention?

Thanks!
