### ISSUE TITLE
Feedback on how to make custom changes to slurm config file

### ISSUE THREAD

**Issue by adebayoj** [aws/aws-parallelcluster#6648]
Hi, we are currently using parallel cluster as a SLURM cluster with a capacity reservation of 3 p4de.24xlarge instances. We've been running into certain issues, but we couldn't find clear feedback on how to address them, so we wanted to check here. I have included our cluster-config-yaml file, and would appreciate feedback. 

## Problem 1: Custom Changes to config files
We would like to make changes to the slurm config files to enable certain behavior. Specificially, we would like to enable the following:
```text
# temp environment changes
PrologFlags             = Alloc,Contain,X11
JobContainerType        = job_container/tmpfs

# this might help make it so that nvidia-smi is isolated
ConstrainDevices        = yes
ConstrainRAMSpace       = yes

# For OOM containment
JobAcctGatherType       = jobacct_gather/cgroup
JobAcctGatherParams     = NoOverMemoryKill

```

```
# make salloc call srun for interactive jobs
LaunchParameters        = use_interactive_step [or] use_interactive_step,enable_nss_slurm
```

However, we've found that we can't set these parameters through the `CustomSlurmSettings` option.  For temp environments, it seems like we might need to create a custom job_container.conf file. However, I currently see no way to do this via the config file. 

Question: can we manually enable all of these options ourselves without repercussions? What would you suggest? 

## Problem 2: Separate partition for root (/) and how to enable usrquota.
We would like to mount root (/) to a separate file system through Lustre or something else. However, it currently says that only a single lustre file system can be used as a part of a given installation. Secondly, we would like to constrain the size of each user's home directory to be a particular size. Can you share how we can enable this programmatically? We could do this manually as described here: http://www.yolinux.com/TUTORIALS/LinuxTutorialQuotas.html, but we are wondering if there are any other alternatives? 

Thanks for the help.

**Comment by adebayoj** [comment]
Adding our cluster configuration file here. 
```
Region: us-west-2
Imds:
  ImdsSupport: v2.0
Image:
  Os: ubuntu2004
  CustomAmi: ami-08f434825b73b442e
HeadNode:
  InstanceType: m5.8xlarge
  Networking:
    SubnetId: xxxx
    ElasticIp: true
  Ssh:
    KeyName: julius-ed
  LocalStorage:
    RootVolume:
      Size: 500
      DeleteOnTermination: true
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - Policy: arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      - Policy: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    S3Access:
      - BucketName: name
        EnableWriteAccess: true
      - BucketName: name
        EnableWriteAccess: true
      - BucketName: name
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    ScaledownIdletime: 60
    CustomSlurmSettings:
    # Slurm accounting settings
    # disable this once accounting is enabled to a database.
      - JobCompType: jobcomp/filetxt
      - JobCompLoc: /home/slurm/slurm-jobcompletions.txt
      - JobAcctGatherType: jobacct_gather/linux
  SlurmQueues:
    - Name: cpu-queue
      ComputeResources:
        - Name: c59xlarge
          Instances:
            - InstanceType: c5.9xlarge
          MinCount: 1 # if min = max then capacity is fixed. If min < max then capacity is dynamic
          MaxCount: 2
      Networking:
        SubnetIds: 
        - subnet-id
      Iam:
        S3Access:
          - BucketName: name
            EnableWriteAccess: true
          - BucketName: guidelabs-users
            EnableWriteAccess: true
          - BucketName: guidelabs-scripts
    - Name: gpu-queue
      Networking:
        SubnetIds: 
          - subnet-id
        PlacementGroup:
          Enabled: false
      ComputeSettings:
        LocalStorage:
          EphemeralVolume:
            MountDir: /scratch
          RootVolume:
            Size: 200
      CapacityReservationTarget:
        CapacityReservationId: capacityreservation-id
      ComputeResources:
        - Name: a100
          InstanceType: p4de.24xlarge
          MinCount: 3 # if min = max then capacity is fixed. If min < max then capacity is dynamic
          MaxCount: 3
          Efa:
            Enabled: true
      Iam:
        S3Access:
          - BucketName: name
            EnableWriteAccess: true
          - BucketName: name
            EnableWriteAccess: true
          - BucketName: name
SharedStorage:
  - MountDir: /fsx
    Name: fsx
    StorageType: FsxLustre
    FsxLustreSettings:
      DeploymentType: PERSISTENT_2
      StorageCapacity: 12000
      DeletionPolicy: Retain
      PerUnitStorageThroughput: 250
Monitoring:
  DetailedMonitoring: true
  Logs:
    CloudWatch:
      Enabled: true
  Dashboards:
    CloudWatch:
      Enabled: true
DirectoryService:
  DomainName: x
  DomainAddr: x
  PasswordSecretArn: x
  DomainReadOnlyUser: x
  GenerateSshKeysForUsers: True
  AdditionalSssdConfigs:
    ldap_auth_disable_tls_never_use_in_production: True
```
