### ISSUE TITLE
Job submit lua plugin failing

### ISSUE THREAD

**Issue by efimov-ay** [aws/aws-parallelcluster#6740]
I need to enable Lua job submit plugin on cluster creation. This plugin enables custom job submission logic programmed through a Lua script `/opt/slurm/etc/job_submit.lua`.

The problem is that this plugin requires `/opt/slurm/etc/job_submit.lua` file to be in place before `slurmctld` starts, otherwise `slurmctld` startup will fail.

I need a mechanism to inject a file to the head node right after all the software is installed, but before it's started. So that we can inject the `job_submit.lua` file into the head node correctly.

**Required Info:**
 - AWS ParallelCluster version [e.g. 3.1.1]: 3.12.0
 - Full cluster configuration without any credentials or personal data.
```
HeadNode:
  CustomActions:
    OnNodeConfigured:
      Args:
        - head
      Script: >-
        s3://MYBUCKET/scripts/postscript.sh
  Iam:
    AdditionalIamPolicies:
      - Policy: '***MASKED_CUSTOM_POLICY_ARN***'
      - Policy: 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
      - Policy: 'arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy'
    S3Access:
      - BucketName: MYBUCKET
        EnableWriteAccess: false
  Image:
    CustomAmi: ami-1234455677
  InstanceType: t3.large
  LocalStorage:
    RootVolume:
      Encrypted: true
      Size: 150
  Networking:
    AdditionalSecurityGroups:
      - sg-1122344
    SubnetId: subnet-11223344
  SharedStorageType: Ebs
  Ssh:
    AllowedIps: 10.0.0.0/8
    KeyName: pcluster_deployer_key-dev
Iam:
  ResourcePrefix: pcluster-devtest-
Image:
  CustomAmi: ami-1234455677
  Os: rocky8
Imds:
  ImdsSupport: v1.0
LoginNodes:
  Pools:
    - Count: 1
      CustomActions:
        OnNodeConfigured:
          Args:
            - login
          Script: >-
            s3://MYBUCKET/scripts/postscript.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: '***MASKED_CUSTOM_POLICY_ARN***'
          - Policy: 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
          - Policy: 'arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy'
      Image:
        CustomAmi: ami-1234455677
      InstanceType: t3.medium
      Name: login
      Networking:
        AdditionalSecurityGroups:
          - sg-1122344
        SubnetIds:
          - subnet-11223344
      Ssh:
        AllowedIps: 10.0.0.0/8
        KeyName: pcluster_deployer_key-dev
Monitoring:
  Alarms:
    Enabled: true
  Dashboards:
    CloudWatch:
      Enabled: true
  DetailedMonitoring: true
  Logs:
    CloudWatch:
      DeletionPolicy: Delete
      Enabled: true
      RetentionInDays: 90
    Rotation:
      Enabled: true
Region: us-west-2
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - AllocationStrategy: lowest-price
      CapacityType: ONDEMAND
      ComputeResources:
        - CustomSlurmSettings:
            CPUSpecList: 1
          DisableSimultaneousMultithreading: true
          DynamicNodePriority: 14000
          Instances:
            - InstanceType: t3.xlarge
          MaxCount: 3
          MinCount: 1
          Name: devtest-xl
          StaticNodePriority: 14000
        - CustomSlurmSettings:
            CPUSpecList: 1
          DisableSimultaneousMultithreading: true
          DynamicNodePriority: 32000
          Instances:
            - InstanceType: t3.2xlarge
          MaxCount: 3
          MinCount: 1
          Name: devtest-2xl
          StaticNodePriority: 32000
      ComputeSettings:
        LocalStorage:
          EphemeralVolume:
            MountDir: /ephemeral
          RootVolume:
            Encrypted: true
            Size: 200
      CustomActions:
        OnNodeConfigured:
          Args:
            - compute
          Script: >-
            s3://MYBUCKET/scripts/postscript.sh
      CustomSlurmSettings:
        AllowQos: gold
      Iam:
        AdditionalIamPolicies:
          - Policy: '***MASKED_CUSTOM_POLICY_ARN***'
          - Policy: 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
          - Policy: 'arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy'
        S3Access:
          - BucketName: MYBUCKET
            EnableWriteAccess: false
      Image:
        CustomAmi: ami-1234455677
      JobExclusiveAllocation: false
      Name: devtest1
      Networking:
        AdditionalSecurityGroups:
          - sg-1122344
        SubnetIds:
          - subnet-11223344
          - subnet-11223345
          - subnet-11223346
          - subnet-11223347
  SlurmSettings:
    CustomSlurmSettings:
      - TaskPluginParam: SlurmdOffSpec
      - PrologFlags: 'Alloc,Contain,X11'
      - DefMemPerCPU: 4096
      - JobSubmitPlugins: "lua"
    Dns:
      HostedZoneId: ZAAAAAAAAAAAAAAAAA
    EnableMemoryBasedScheduling: true
    MungeKeySecretArn: '********MASKED********'
    QueueUpdateStrategy: DRAIN
    ScaledownIdletime: 30

```
 - Cluster name: devtest
 - Output of `pcluster describe-cluster` command.

**Bug description and how to reproduce:**

1. Create the cluster from config above using `pcluster create-cluster`
2. Cluster creation fails:
    - in the `slurmd.log` ther eare messages about "job_submit.lua not found"

**Comment by hanwen-cluster** [comment]
Hi Alexander,

Apologies for the late reply.

Configure LUA with OnNodeStart is the best solution. You mentioned some directories don't exist. Are you blocked by this (i.e. can you create those directories as part of the OnNodeStart script)?

Thank you,
Hanwen

**Comment by gmarciani** [comment]
Hi @efimov-ay ,

I tried with the following setup and the LUA script works as expected.
Please notice that the script that configured the LUA plugins must be executed as `OnNodeStart` action from the Head Node.

PC version: 3.12.0

I was able to make the LUA plugin work with the following setup.

PC version: 3.12.0

Cluster config:

```
Region: us-east-1
Image:
  Os: alinux2
HeadNode:
  InstanceType: t3.medium
  Networking:
    SubnetId: REDACTED
  Ssh:
    KeyName: REDACTED
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - Policy: arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
  CustomActions:
    OnNodeStart:
      Script: s3://REDACTED/pcluster-configurations/cluster-config/lua/Head-OnNodeStart.sh
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    QueueUpdateStrategy: DRAIN
    CustomSlurmSettings:
      - JobSubmitPlugins: lua
  SlurmQueues:
    - Name: q1
      ComputeResources:
        - Name: cr1
          InstanceType: t3.small
          MinCount: 1
          MaxCount: 3
      Networking:
        SubnetIds:
          - REDACTED
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
```

where `Head-OnNodeStart.sh` is:

```
#!/bin/bash
set -e

echo "Executing $0"

aws s3 cp s3://REDACTED/pcluster-configurations/cluster-config/lua/job_submit.lua /opt/slurm/etc/job_submit.lua
chmod 0644 /opt/slurm/etc/job_submit.lua
```

and `job_submit.lua` is:

```
--[[

 Example lua script demonstrating the Slurm job_submit/lua interface.
 This is only an example, not meant for use in its current form.

 For use, this script should be copied into a file name "job_submit.lua"
 in the same directory as the Slurm configuration file, slurm.conf.

 Documentation: https://slurm.schedmd.com/job_submit_plugins.html

--]]

function slurm_job_submit(job_desc, part_list, submit_uid)
	slurm.log_info("CUSTOM LUA PLUGIN: EXECUTING slurm_job_submit")
	return slurm.SUCCESS
end

function slurm_job_modify(job_desc, job_rec, part_list, modify_uid)
	slurm.log_info("CUSTOM LUA PLUGIN: EXECUTING slurm_job_modify")
	return slurm.SUCCESS
end

slurm.log_info("CUSTOM LUA PLUGIN: initialized")
return slurm.SUCCESS
```

**Comment by ChristianKniep** [comment]
Hey there, what am I missing?

**Update**: I did miss the `CustomSlurmSettings` :)
```
Scheduler: slurm
  SlurmSettings:
    QueueUpdateStrategy: DRAIN
    CustomSlurmSettings:
      - JobSubmitPlugins: lua
```

I got lua configured:
```
$ scontrol show config | grep -E 'JobSubmit'
JobSubmitPlugins        = lua
```
The script is where it is supposed to be
```
$ ls -l /opt/slurm/etc/job_submit.lua
-rw-r--r-- 1 root root 381 Oct  6 08:48 /opt/slurm/etc/job_submit.lua
$ cat /opt/slurm/etc/job_submit.lua
function slurm_job_submit(job_desc, part_list, submit_uid)
	slurm.log_info("CUSTOM LUA PLUGIN: EXECUTING slurm_job_submit")
	return slurm.SUCCESS
end

function slurm_job_modify(job_desc, job_rec, part_list, modify_uid)
	slurm.log_info("CUSTOM LUA PLUGIN: EXECUTING slurm_job_modify")
	return slurm.SUCCESS
end

slurm.log_info("CUSTOM LUA PLUGIN: initialized")
return slurm.SUCCESS
```
But it won't trigger...
