### ISSUE TITLE
Building custom AMI on Rocky 8.10 with 3.13.0 fails due to rustc version being 1.79 instead of 1.82

### ISSUE THREAD

**Issue by gwolski** [aws/aws-parallelcluster#6819]
Building a parallelcluster AMI overlaying parallecluster on my custom Rocky8.10 AMI.
I take my custom AMI and then run the pcluster build-image process.

The process fails at the ParallelClusterImage step.  Looking at the Cloudwatch logs, I see:

![Image](https://github.com/user-attachments/assets/657407c8-6f45-4d60-8335-ee8594c88d8a)

According to Redh8.10, 1.75 is base rev of rustc for RHEL8/Rocky8.10.
That is what I have running on my 3.11.1 cluster head node.

```
% rustc --version
rustc 1.75.0 (82e1608df 2023-12-21) (Red Hat 1.75.0-1.module+el8.10.0+1668+84166756)
```

Nonetheless, I just confirmed that if I try to install rustc on a Rocky 8 machine, I get 1.79.  So you must be installing it somehow, using latest release for RHEL8.10/Rocky8.10.

Nonetheless, ParallelClusterImage step fails.  

I also tried to build with the community Rocky8.10 ami and it too failed.  Here is my config file that I have in pcluster-3-13-0-Rocky-8-10-x86-64-ami-04310224db1f2a278.yml:

```
# parallelcluster template build file
# This comes from the parallelcluster documentation.
# This file is fed to pcluster to build a parallecluster AMI.
#
# ami-04310224db1f2a278 is generic community Rocky 8.10
#
Image:
  Name: pcluster-3-13-0-Rocky-8-10-x86-64-ami-04310224db1f2a278
  RootVolume:
    Size: 45

Build:
  Imds:
    ImdsSupport: v2.0
  InstanceType: m6a.large # 2 vcpus/8GB
  SubnetId: subnet-0d4e3914a7XXXXXX
  SecurityGroupIds:
    - sg-04f99035XXXXXXX # can be any security group that allows outbound connections. Don't need inbound.
  ParentImage: ami-04310224db1f2a278
  UpdateOsPackages:
    Enabled: false

DevSettings:
  TerminateInstanceOnFailure: true
```
The command I used to submit the above file is:
```
pcluster build-image --image-id pcluster-3-13-0-Rocky-8-10-x86-64-ami-04310224db1f2a278 --image-configuration pcluster-3-13-0-Rocky-8-10-x86-64-ami-04310224db1f2a278.yml --region us-west-2
```
Any workaround/remediation?
