### ISSUE TITLE
(3.8.0 - 3.13.1) Update-Cluster, Update-Compute-Fleet may fail when Compute Resources use an expired Capacity Reservation

### ISSUE THREAD

**Issue by hehe7318** [aws/aws-parallelcluster#6870]
# The issue
The following operations may fail: 

* `pcluster update-cluster`
* `pcluster update-compute-fleet`

With the error message

`Unable to parse configuration file. An error occurred when calling the DescribeCapacityReservations operation: The capacity reservation ID 'cr-xxxxx' was not found`

When 

1. Current cluster configuration includes a [`ComputeResources`](https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#Scheduling-v3-SlurmQueues-ComputeResources) entry with a [`CapacityReservationId`](https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmQueues-ComputeResources-CapacityReservationId) 
2. The specified Capacity Reservation has expired
3. No [`InstanceType`](https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmQueues-ComputeResources-InstanceType) is specified within the same ComputeResources entry

For example

```
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: string
      ComputeResources:
        - Name: string
          MinCount: integer
          MaxCount: integer
          # InstanceType is missing
          CapacityReservationTarget:
            # The Capacity Reservation below is expired or cancelled
            CapacityReservationId: cr-01234567890abcdef
```

# Affected ParallelCluster versions, OSes and schedulers

All ParallelCluster versions from 3.8.0 to 3.13.1 with the Slurm scheduler on all OSes.

# Mitigation

You can find a detailed explanation and the mitigation of the problem [here](https://github.com/aws/aws-parallelcluster/wiki/(3.8.0-%E2%80%90-3.13.1)-Update%E2%80%90Cluster,-Update%E2%80%90Compute%E2%80%90Fleet-may-fail-when-Compute-Resources-use-an-expired-Capacity-Reservation).
